/**
 * Fruehstueck & Buffet — Handgriffe, fuenfsprachig.
 *
 * Sprachen: de (Grundsprache), en, pl, hr, sr
 * Kroatisch und Serbisch sind eng verwandt; wo sich die Woerter wirklich
 * unterscheiden, ist das beruecksichtigt (kruh/hleb, žlica/kašika,
 * mrkva/šargarepa, tjedan/nedelja, točno/tačno, tko/ko, što/šta).
 * Serbisch in lateinischer Schrift.
 *
 * Fachwerte: nur allgemein anerkannte Grenzen — Kuehlkette hoechstens 7 °C,
 * Heisshaltung mindestens 65 °C, 14 kennzeichnungspflichtige Allergene
 * (EU-LMIV). Standzeiten und Kerntemperaturen beim Wiedererhitzen stehen
 * bewusst ohne Zahl: "nach Hausvorgabe".
 */

const buffetAufbau = {
  id: "bf-aufbau",
  title: { de: "Buffet aufbauen", en: "Setting up the buffet", pl: "Przygotowanie bufetu",
           hr: "Postavljanje švedskog stola", sr: "Postavljanje švedskog stola" },
  goal: { de: "Du baust das Buffet so auf, dass warm warm bleibt und kalt kalt.",
          en: "You set up the buffet so hot stays hot and cold stays cold.",
          pl: "Ustawiasz bufet tak, by ciepłe zostało ciepłe, a zimne zimne.",
          hr: "Postaviš švedski stol tako da toplo ostane toplo, a hladno hladno.",
          sr: "Postaviš švedski sto tako da toplo ostane toplo, a hladno hladno." },
  minutes: 5,
  stages: [
    { id: "bf-aufbau-s1",
      goal: { de: "Du siehst die fünf Handgriffe vor dem ersten Gast und erkennst, worauf die zwei Anzeigen hinweisen.",
              en: "You see the five moves before the first guest and recognise what the two gauges are telling you.",
              pl: "Widzisz pięć kroków przed pierwszym gościem i rozpoznajesz, co pokazują dwa wskaźniki.",
              hr: "Vidiš pet koraka prije prvog gosta i prepoznaješ što pokazuju dva mjerača.",
              sr: "Vidiš pet koraka pre prvog gosta i prepoznaješ šta pokazuju dva merača." },
      steps: [
        {
          type: "demo",
          scene: "buffet",
          title: { de: "Schau dir den Aufbau an", en: "Watch the setup", pl: "Obejrzyj przygotowanie",
                   hr: "Pogledaj postavljanje", sr: "Pogledaj postavljanje" },
          intro: { de: "Fünf Handgriffe vor dem ersten Gast. Achte auf die zwei Anzeigen — sie entscheiden, ob das Essen raus darf.",
                   en: "Five moves before the first guest. Watch the two displays — they decide whether the food may go out.",
                   pl: "Pięć czynności przed pierwszym gościem. Patrz na dwa wskaźniki — one decydują, czy jedzenie może wyjść.",
                   hr: "Pet radnji prije prvog gosta. Pazi na dva pokazivača — oni odlučuju smije li hrana van.",
                   sr: "Pet radnji pre prvog gosta. Pazi na dva pokazivača — oni odlučuju sme li hrana napolje." },
          frames: [
            { caption: { de: "Niesschutz prüfen", en: "Check the sneeze guard", pl: "Sprawdź osłonę",
                         hr: "Provjeri zaštitno staklo", sr: "Proveri zaštitno staklo" },
              detail: { de: "Scheibe sitzt fest und ist sauber. Sie hält Husten und Niesen der Gäste vom offenen Essen fern.",
                        en: "The pane sits firm and is clean. It keeps guests' coughs and sneezes away from open food.",
                        pl: "Szyba siedzi pewnie i jest czysta. Chroni odkryte jedzenie przed kaszlem i kichaniem gości.",
                        hr: "Staklo čvrsto stoji i čisto je. Drži kašalj i kihanje gostiju dalje od otvorene hrane.",
                        sr: "Staklo čvrsto stoji i čisto je. Drži kašalj i kijanje gostiju dalje od otvorene hrane." } },
            { caption: { de: "Thermometer und Liste holen", en: "Get thermometer and log", pl: "Weź termometr i listę",
                         hr: "Uzmi termometar i listu", sr: "Uzmi termometar i listu" },
              detail: { de: "Ohne Messgerät ist jede Temperatur nur geschätzt. Die Liste ist dein Nachweis, dass gemessen wurde.",
                        en: "Without a device every temperature is just a guess. The log is your proof that you measured.",
                        pl: "Bez miernika każda temperatura to tylko domysł. Lista to dowód, że mierzyłeś.",
                        hr: "Bez mjerača je svaka temperatura samo procjena. Lista je tvoj dokaz da si mjerio.",
                        sr: "Bez merača je svaka temperatura samo procena. Lista je tvoj dokaz da si merio." } },
            { caption: { de: "Warmhaltebehälter aufheizen", en: "Heat the hot holding unit", pl: "Rozgrzej podgrzewacz",
                         hr: "Zagrij grijaću posudu", sr: "Zagrej grejnu posudu" },
              detail: { de: "Erst einfüllen, wenn das Gerät mindestens 65 °C hält. Darunter wachsen Keime im warmen Essen schnell.",
                        en: "Only fill it once the unit holds at least 65 °C. Below that, germs grow fast in warm food.",
                        pl: "Napełniaj dopiero, gdy urządzenie trzyma co najmniej 65 °C. Poniżej zarazki szybko rosną w ciepłym jedzeniu.",
                        hr: "Puni tek kad uređaj drži najmanje 65 °C. Ispod toga klice se u toploj hrani brzo množe.",
                        sr: "Puni tek kad uređaj drži najmanje 65 °C. Ispod toga klice se u toploj hrani brzo množe." } },
            { caption: { de: "Kühlung kontrollieren", en: "Check the chilled unit", pl: "Sprawdź chłodzenie",
                         hr: "Provjeri hlađenje", sr: "Proveri hlađenje" },
              detail: { de: "Wurst, Käse, Milch und Joghurt dürfen höchstens 7 °C haben. Erst dann kommt die kalte Ware raus.",
                        en: "Cold cuts, cheese, milk and yoghurt may be at most 7 °C. Only then the cold items go out.",
                        pl: "Wędlina, ser, mleko i jogurt mogą mieć najwyżej 7 °C. Dopiero wtedy zimne produkty wychodzą.",
                        hr: "Narezak, sir, mlijeko i jogurt smiju imati najviše 7 °C. Tek onda hladna roba ide van.",
                        sr: "Narezak, sir, mleko i jogurt smeju imati najviše 7 °C. Tek onda hladna roba ide napolje." } },
            { caption: { de: "Freigeben und eintragen", en: "Release and log it", pl: "Zwolnij i zapisz",
                         hr: "Pusti i upiši", sr: "Pusti i upiši" },
              detail: { de: "Beide Werte in die Liste, dann erst Zangen auflegen und Schilder stellen. Ein eingetragener Wert schützt dich und das Haus.",
                        en: "Both values into the log, then put out tongs and signs. A logged value protects you and the house.",
                        pl: "Obie wartości na listę, potem kładziesz szczypce i stawiasz tabliczki. Zapisana wartość chroni ciebie i hotel.",
                        hr: "Obje vrijednosti u listu, tek onda hvataljke i natpisi. Upisana vrijednost štiti tebe i kuću.",
                        sr: "Obe vrednosti u listu, tek onda hvataljke i natpisi. Upisana vrednost štiti tebe i kuću." } }
          ]
        },
      ] },
    { id: "bf-aufbau-s2",
      goal: { de: "Du baust das Buffet in der richtigen Reihenfolge auf — warm und kalt getrennt.",
              en: "You set the buffet up in the right order — hot and cold kept apart.",
              pl: "Ustawiasz bufet we właściwej kolejności — ciepłe oddzielnie od zimnego.",
              hr: "Postavljaš švedski stol pravilnim redoslijedom — toplo odvojeno od hladnog.",
              sr: "Postavljaš švedski sto pravilnim redosledom — toplo odvojeno od hladnog." },
      steps: [
        {
          type: "sequence",
          prompt: { de: "Jetzt du — in welcher Reihenfolge baust du auf?",
                    en: "Now you — in what order do you set up?",
                    pl: "Teraz ty — w jakiej kolejności ustawiasz?",
                    hr: "Sada ti — kojim redoslijedom postavljaš?",
                    sr: "Sada ti — kojim redosledom postavljaš?" },
      steps: [
            { de: "Hände waschen und saubere Schürze", en: "Wash hands, clean apron", pl: "Umyj ręce, czysty fartuch",
              hr: "Operi ruke, čista pregača", sr: "Operi ruke, čista kecelja" },
            { de: "Niesschutz und Flächen prüfen", en: "Check sneeze guard and surfaces", pl: "Sprawdź osłonę i powierzchnie",
              hr: "Provjeri zaštitno staklo i površine", sr: "Proveri zaštitno staklo i površine" },
            { de: "Geräte einschalten und vorheizen oder vorkühlen", en: "Switch units on to preheat or precool",
              pl: "Włącz urządzenia, nagrzej lub schłódź", hr: "Uključi uređaje, zagrij ili ohladi",
              sr: "Uključi uređaje, zagrej ili ohladi" },
            { de: "Speisen einsetzen, warm und kalt getrennt", en: "Put the food in, hot and cold apart",
              pl: "Włóż potrawy, ciepłe osobno od zimnych", hr: "Stavi jela, toplo odvojeno od hladnog",
              sr: "Stavi jela, toplo odvojeno od hladnog" },
            { de: "Temperaturen messen und eintragen", en: "Measure temperatures and log them",
              pl: "Zmierz temperatury i zapisz", hr: "Izmjeri temperature i upiši",
              sr: "Izmeri temperature i upiši" },
            { de: "Zangen, Allergen- und Namensschilder auflegen", en: "Put out tongs, allergen and name signs",
              pl: "Połóż szczypce, tabliczki z alergenami i nazwami",
              hr: "Stavi hvataljke, natpise s alergenima i nazivima",
              sr: "Stavi hvataljke, natpise sa alergenima i nazivima" }
          ],
          explain: { de: "Erst Gerät, dann Essen: Kalte Ware in einem noch warmen Behälter verliert die Kühlkette schon beim Einsetzen.",
                     en: "Unit first, food second: cold items placed in a still-warm unit break the cold chain right away.",
                     pl: "Najpierw urządzenie, potem jedzenie: zimny towar w ciepłym pojemniku traci łańcuch chłodniczy od razu.",
                     hr: "Prvo uređaj, onda hrana: hladna roba u još toploj posudi gubi hladni lanac već pri stavljanju.",
                     sr: "Prvo uređaj, onda hrana: hladna roba u još toploj posudi gubi hladni lanac već pri stavljanju." }
        },
      ] },
    { id: "bf-aufbau-s3",
      goal: { de: "Du entscheidest an der Temperatur, ob das Buffet öffnen darf, und prüfst vorher alles Nötige.",
              en: "You decide from the temperature whether the buffet may open, and check everything needed beforehand.",
              pl: "Na podstawie temperatury decydujesz, czy bufet może się otworzyć, i wcześniej sprawdzasz wszystko, co konieczne.",
              hr: "Po temperaturi odlučuješ smije li se švedski stol otvoriti i prije toga provjeriš sve potrebno.",
              sr: "Po temperaturi odlučuješ da li švedski sto sme da se otvori i pre toga proveriš sve potrebno." },
      steps: [
        {
          type: "decide",
          prompt: { de: "Das Thermometer zeigt in der Kühlung 11 °C. Das Buffet öffnet in fünf Minuten. Was tust du?",
                    en: "The thermometer shows 11 °C in the chilled unit. The buffet opens in five minutes. What do you do?",
                    pl: "Termometr w chłodzeniu pokazuje 11 °C. Bufet otwiera się za pięć minut. Co robisz?",
                    hr: "Termometar u hlađenju pokazuje 11 °C. Švedski stol otvara se za pet minuta. Što ćeš učiniti?",
                    sr: "Termometar u hlađenju pokazuje 11 °C. Švedski sto otvara se za pet minuta. Šta ćeš uraditi?" },
          options: [
            { de: "Trotzdem aufbauen, es ist ja nur kurz", en: "Set it up anyway, it's only for a short time",
              pl: "Mimo to ustaw, to tylko chwila", hr: "Ipak postavi, kratko je", sr: "Ipak postavi, kratko je" },
            { de: "Einen niedrigeren Wert eintragen, damit die Liste passt",
              en: "Log a lower value so the sheet looks right",
              pl: "Wpisz niższą wartość, żeby lista się zgadzała",
              hr: "Upiši nižu vrijednost da lista štima", sr: "Upiši nižu vrednost da lista štima" },
            { de: "Ware kalt lagern, Küche informieren und erst bei höchstens 7 °C aufbauen",
              en: "Store the items cold, tell the kitchen and set up only at 7 °C or below",
              pl: "Schowaj towar do chłodu, powiedz kuchni i ustaw dopiero przy najwyżej 7 °C",
              hr: "Spremi robu na hladno, javi kuhinji i postavi tek na najviše 7 °C",
              sr: "Skloni robu na hladno, javi kuhinji i postavi tek na najviše 7 °C" },
            { de: "Eiswürfel dazulegen und nichts sagen", en: "Add ice cubes and say nothing",
              pl: "Dołóż kostki lodu i nic nie mów", hr: "Dodaj kocke leda i ne reci ništa",
              sr: "Dodaj kocke leda i ne reci ništa" }
          ],
          answer: 2,
          explain: { de: "Höchstens 7 °C ist eine Grenze, keine Empfehlung. Ein falscher Eintrag ist schlimmer als ein warmes Gerät: Er macht den Fehler unsichtbar.",
                     en: "7 °C at most is a limit, not a suggestion. A false entry is worse than a warm unit: it hides the problem.",
                     pl: "Najwyżej 7 °C to granica, nie sugestia. Fałszywy wpis jest gorszy niż ciepłe urządzenie: ukrywa błąd.",
                     hr: "Najviše 7 °C je granica, ne preporuka. Lažan upis gori je od toplog uređaja: skriva grešku.",
                     sr: "Najviše 7 °C je granica, ne preporuka. Lažan upis gori je od toplog uređaja: skriva grešku." }
        },
        {
          type: "checklist",
          prompt: { de: "Was muss stimmen, bevor der erste Gast kommt? Wähle alles Richtige.",
                    en: "What has to be right before the first guest arrives? Select everything correct.",
                    pl: "Co musi się zgadzać, zanim przyjdzie pierwszy gość? Zaznacz wszystko poprawne.",
                    hr: "Što mora biti točno prije prvog gosta? Odaberi sve točno.",
                    sr: "Šta mora biti tačno pre prvog gosta? Izaberi sve tačno." },
          items: [
            { label: { de: "Warme Speisen bei mindestens 65 °C", en: "Hot food at 65 °C or above",
                       pl: "Ciepłe potrawy przy co najmniej 65 °C", hr: "Topla jela na najmanje 65 °C",
                       sr: "Topla jela na najmanje 65 °C" }, correct: true },
            { label: { de: "Kalte Speisen bei höchstens 7 °C", en: "Cold food at 7 °C or below",
                       pl: "Zimne potrawy przy najwyżej 7 °C", hr: "Hladna jela na najviše 7 °C",
                       sr: "Hladna jela na najviše 7 °C" }, correct: true },
            { label: { de: "Für jede Speise eine eigene Zange oder Kelle",
                       en: "A separate tongs or ladle for each dish",
                       pl: "Osobne szczypce lub łyżka do każdej potrawy",
                       hr: "Zasebna hvataljka ili žlica za svako jelo",
                       sr: "Zasebna hvataljka ili kašika za svako jelo" }, correct: true },
            { label: { de: "Die 14 kennzeichnungspflichtigen Allergene sind am Schild ablesbar",
                       en: "The 14 allergens requiring labelling are readable on the sign",
                       pl: "14 alergenów podlegających oznaczeniu jest czytelnych na tabliczce",
                       hr: "14 alergena koji se moraju označiti čitljivo je na natpisu",
                       sr: "14 alergena koji se moraju označiti čitljivo je na natpisu" }, correct: true },
            { label: { de: "Eine Zange für alles, das spart Abwasch",
                       en: "One pair of tongs for everything, saves washing up",
                       pl: "Jedne szczypce do wszystkiego, mniej zmywania",
                       hr: "Jedna hvataljka za sve, manje pranja",
                       sr: "Jedna hvataljka za sve, manje pranja" }, correct: false },
            { label: { de: "Temperaturen erst nach dem Frühstück aus dem Kopf eintragen",
                       en: "Log the temperatures from memory after breakfast",
                       pl: "Temperatury wpisać z pamięci dopiero po śniadaniu",
                       hr: "Temperature upisati po sjećanju tek nakon doručka",
                       sr: "Temperature upisati po sećanju tek posle doručka" }, correct: false }
          ],
          explain: { de: "Zwei Temperaturgrenzen, eine Zange je Speise, ein Allergenschild — das ist der ganze Aufbau. Aus dem Kopf eingetragene Werte sind kein Nachweis.",
                     en: "Two temperature limits, one tongs per dish, one allergen sign — that's the whole setup. Values written from memory are no proof.",
                     pl: "Dwie granice temperatury, jedne szczypce na potrawę, jedna tabliczka alergenów — to cały bufet. Wartości z pamięci nie są dowodem.",
                     hr: "Dvije granice temperature, jedna hvataljka po jelu, jedan natpis s alergenima — to je cijelo postavljanje. Vrijednosti po sjećanju nisu dokaz.",
                     sr: "Dve granice temperature, jedna hvataljka po jelu, jedan natpis sa alergenima — to je celo postavljanje. Vrednosti po sećanju nisu dokaz." }
        }
      ] },
  ]
};

const nachfuellenHygiene = {
  id: "bf-nachfuellen",
  title: { de: "Nachfüllen & Hygiene im Betrieb", en: "Refilling and hygiene during service",
           pl: "Uzupełnianie i higiena podczas serwisu", hr: "Nadopunjavanje i higijena tijekom usluge",
           sr: "Dopunjavanje i higijena tokom usluge" },
  goal: { de: "Du füllst nach, ohne Altes und Neues zu mischen — und weißt, wann etwas weg muss.",
          en: "You refill without mixing old and new — and know when something has to go.",
          pl: "Uzupełniasz bez mieszania starego z nowym — i wiesz, kiedy coś musi zniknąć.",
          hr: "Nadopunjavaš bez miješanja starog i novog — i znaš kada nešto mora van.",
          sr: "Dopunjavaš bez mešanja starog i novog — i znaš kada nešto mora napolje." },
  minutes: 5,
  stages: [
    { id: "bf-nachfuellen-s1",
      goal: { de: "Du füllst eine fast leere Platte in der richtigen Reihenfolge nach, ohne Altes und Neues zu mischen.",
              en: "You refill an almost empty platter in the right order, without mixing old and new.",
              pl: "Uzupełniasz prawie pusty półmisek we właściwej kolejności, nie mieszając starego z nowym.",
              hr: "Nadopunjavaš gotovo prazan pladanj pravilnim redoslijedom, bez miješanja starog i novog.",
              sr: "Dopunjavaš gotovo prazan poslužavnik pravilnim redosledom, bez mešanja starog i novog." },
      steps: [
        {
          type: "sequence",
          prompt: { de: "Die Wurstplatte ist fast leer. Was tust du in welcher Reihenfolge?",
                    en: "The cold cuts platter is nearly empty. What do you do, in what order?",
                    pl: "Półmisek z wędliną jest prawie pusty. Co robisz i w jakiej kolejności?",
                    hr: "Pladanj s narescima je gotovo prazan. Što radiš i kojim redoslijedom?",
                    sr: "Poslužavnik sa narescima je skoro prazan. Šta radiš i kojim redosledom?" },
      steps: [
            { de: "Hände waschen", en: "Wash your hands", pl: "Umyj ręce", hr: "Operi ruke", sr: "Operi ruke" },
            { de: "Alte Platte ganz herausnehmen", en: "Take the old platter out completely",
              pl: "Wyjmij stary półmisek w całości", hr: "Izvadi stari pladanj u cijelosti",
              sr: "Izvadi stari poslužavnik u celosti" },
            { de: "Frische Platte aus der Kühlung holen", en: "Get a fresh platter from the fridge",
              pl: "Przynieś świeży półmisek z chłodni", hr: "Donesi svježi pladanj iz hladnjaka",
              sr: "Donesi svež poslužavnik iz frižidera" },
            { de: "Einsetzen und saubere Zange auflegen", en: "Put it in and add clean tongs",
              pl: "Włóż i połóż czyste szczypce", hr: "Stavi i dodaj čistu hvataljku",
              sr: "Stavi i dodaj čistu hvataljku" },
            { de: "Temperatur messen und eintragen", en: "Measure the temperature and log it",
              pl: "Zmierz temperaturę i zapisz", hr: "Izmjeri temperaturu i upiši", sr: "Izmeri temperaturu i upiši" },
            { de: "Alte Reste nach Hausvorgabe behandeln", en: "Handle the old leftovers as the house rule says",
              pl: "Z resztkami postąp według zasad hotelu", hr: "S ostatkom postupi prema uputi kuće",
              sr: "Sa ostatkom postupi prema uputstvu kuće" }
          ],
          explain: { de: "Die alte Platte kommt ganz raus, bevor die neue kommt. Sonst liegt Ware von heute früh unter frischer Ware und niemand weiß mehr, wie alt sie ist.",
                     en: "The old platter comes out completely before the new one goes in. Otherwise this morning's food sits under fresh food and nobody knows its age.",
                     pl: "Stary półmisek wychodzi w całości, zanim wejdzie nowy. Inaczej towar z rana leży pod świeżym i nikt nie wie, ile ma czasu.",
                     hr: "Stari pladanj izlazi u cijelosti prije nego uđe novi. Inače jutrošnja roba leži ispod svježe i nitko više ne zna koliko je stara.",
                     sr: "Stari poslužavnik izlazi u celosti pre nego uđe novi. Inače jutrošnja roba leži ispod sveže i niko više ne zna koliko je stara." }
        },
      ] },
    { id: "bf-nachfuellen-s2",
      goal: { de: "Du erkennst, was nie zurück ins Buffet darf, und benutzt zum Nachfüllen sauberes Werkzeug.",
              en: "You recognise what must never go back into the buffet, and use clean tools for refilling.",
              pl: "Rozpoznajesz, co nigdy nie może wrócić na bufet, i do uzupełniania używasz czystych narzędzi.",
              hr: "Prepoznaješ što se nikad ne smije vratiti na švedski stol i za nadopunjavanje koristiš čist pribor.",
              sr: "Prepoznaješ šta nikad ne sme da se vrati na švedski sto i za dopunjavanje koristiš čist pribor." },
      steps: [
        {
          type: "decide",
          prompt: { de: "Eine Gästin nimmt die Zange aus dem Käse und legt sie in den Schinken. Was tust du?",
                    en: "A guest takes the tongs from the cheese and puts them in the ham. What do you do?",
                    pl: "Gościni bierze szczypce z sera i wkłada je do szynki. Co robisz?",
                    hr: "Gošća uzme hvataljku iz sira i stavi je u šunku. Što ćeš učiniti?",
                    sr: "Gošća uzme hvataljku iz sira i stavi je u šunku. Šta ćeš uraditi?" },
          options: [
            { de: "Nichts, die Gäste dürfen das selbst entscheiden", en: "Nothing, guests can decide that themselves",
              pl: "Nic, goście sami decydują", hr: "Ništa, gosti sami odlučuju", sr: "Ništa, gosti sami odlučuju" },
            { de: "Zange zurück in den Käse legen", en: "Put the tongs back into the cheese",
              pl: "Odłóż szczypce z powrotem do sera", hr: "Vrati hvataljku u sir", sr: "Vrati hvataljku u sir" },
            { de: "Freundlich eine frische Zange bringen und die gebrauchte zum Spülen geben",
              en: "Politely bring fresh tongs and send the used ones to be washed",
              pl: "Uprzejmie przynieś świeże szczypce, a użyte oddaj do zmywania",
              hr: "Ljubazno donesi čistu hvataljku, a korištenu daj na pranje",
              sr: "Ljubazno donesi čistu hvataljku, a korišćenu daj na pranje" },
            { de: "Zange kurz am Tuch abwischen und liegen lassen",
              en: "Wipe the tongs on a cloth and leave them there",
              pl: "Przetrzyj szczypce ścierką i zostaw", hr: "Obriši hvataljku krpom i ostavi",
              sr: "Obriši hvataljku krpom i ostavi" }
          ],
          answer: 2,
          explain: { de: "Jede Speise hat ihre eigene Zange, weil Allergene mitwandern: Milch im Schinken kann eine Gästin ins Krankenhaus bringen. Ein Tuch entfernt das nicht.",
                     en: "Each dish has its own tongs because allergens travel: milk in the ham can send a guest to hospital. A cloth does not remove that.",
                     pl: "Każda potrawa ma własne szczypce, bo alergeny wędrują: mleko w szynce może wysłać gościa do szpitala. Ścierka tego nie usuwa.",
                     hr: "Svako jelo ima svoju hvataljku jer alergeni putuju: mlijeko u šunki može gošću odvesti u bolnicu. Krpa to ne uklanja.",
                     sr: "Svako jelo ima svoju hvataljku jer alergeni putuju: mleko u šunki može gošću odvesti u bolnicu. Krpa to ne uklanja." }
        },
        {
          type: "checklist",
          prompt: { de: "Was ist im laufenden Frühstück richtig? Wähle alles Richtige.",
                    en: "What is correct during an ongoing breakfast service? Select everything correct.",
                    pl: "Co jest poprawne podczas trwającego śniadania? Zaznacz wszystko poprawne.",
                    hr: "Što je točno tijekom doručka? Odaberi sve točno.",
                    sr: "Šta je tačno tokom doručka? Izaberi sve tačno." },
          items: [
            { label: { de: "Hände waschen vor jedem Nachfüllen und nach jedem Abräumen",
                       en: "Wash hands before every refill and after every clear-down",
                       pl: "Myj ręce przed każdym uzupełnieniem i po każdym sprzątaniu",
                       hr: "Operi ruke prije svakog nadopunjavanja i nakon svakog raspremanja",
                       sr: "Operi ruke pre svakog dopunjavanja i posle svakog raspremanja" }, correct: true },
            { label: { de: "Was auf den Boden gefallen ist, kommt weg — auch verpacktes Brot",
                       en: "Anything that fell on the floor goes in the bin — even wrapped bread",
                       pl: "Co spadło na podłogę, idzie do kosza — także zapakowany chleb",
                       hr: "Što je palo na pod, ide van — i zapakirani kruh",
                       sr: "Što je palo na pod, ide napolje — i zapakovani hleb" }, correct: true },
            { label: { de: "Temperaturen werden während des Betriebs weiter gemessen und eingetragen",
                       en: "Temperatures keep being measured and logged during service",
                       pl: "Temperatury mierzy się i zapisuje także w trakcie serwisu",
                       hr: "Temperature se mjere i upisuju i tijekom usluge",
                       sr: "Temperature se mere i upisuju i tokom usluge" }, correct: true },
            { label: { de: "Frisches Rührei auf den alten Rest im Behälter nachkippen",
                       en: "Tip fresh scrambled egg onto the old leftovers in the tray",
                       pl: "Dolewać świeżą jajecznicę na starą resztę w pojemniku",
                       hr: "Dosipati svježa kajgana na stari ostatak u posudi",
                       sr: "Dosipati sveža kajgana na stari ostatak u posudi" }, correct: false },
            { label: { de: "Vom Gast zurückgestellte Ware zurück ins Buffet legen",
                       en: "Put food a guest handed back into the buffet again",
                       pl: "Odłożyć z powrotem na bufet to, co gość oddał",
                       hr: "Vratiti na stol ono što je gost odložio",
                       sr: "Vratiti na sto ono što je gost odložio" }, correct: false },
            { label: { de: "Mit derselben Zange nachfüllen, mit der die Gäste gearbeitet haben",
                       en: "Refill with the same tongs the guests have been using",
                       pl: "Uzupełniać tymi samymi szczypcami, których używali goście",
                       hr: "Nadopunjavati istom hvataljkom kojom su radili gosti",
                       sr: "Dopunjavati istom hvataljkom kojom su radili gosti" }, correct: false }
          ],
          explain: { de: "Was einmal am Gast war oder am Boden lag, kommt nie zurück ins Buffet. Und Nachfüllen ist Küchenarbeit — dafür nimmst du sauberes Werkzeug, keine Gästezange.",
                     en: "What has been with a guest or on the floor never returns to the buffet. And refilling is kitchen work — use clean tools, not the guests' tongs.",
                     pl: "Co było u gościa albo na podłodze, nigdy nie wraca na bufet. A uzupełnianie to praca kuchni — bierzesz czyste narzędzie, nie szczypce gości.",
                     hr: "Što je bilo kod gosta ili na podu, nikad se ne vraća na stol. A nadopunjavanje je kuhinjski posao — uzmi čist pribor, ne gostovu hvataljku.",
                     sr: "Što je bilo kod gosta ili na podu, nikad se ne vraća na sto. A dopunjavanje je kuhinjski posao — uzmi čist pribor, ne gostovu hvataljku." }
        },
      ] },
    { id: "bf-nachfuellen-s3",
      goal: { de: "Du weißt, dass du bei Durchfall nicht ans Buffet darfst, und meldest dich rechtzeitig.",
              en: "You know that with diarrhoea you must not work at the buffet, and you report it in time.",
              pl: "Wiesz, że przy biegunce nie wolno ci pracować przy bufecie, i zgłaszasz to na czas.",
              hr: "Znaš da s proljevom ne smiješ na švedski stol i javiš se na vrijeme.",
              sr: "Znaš da sa prolivom ne smeš na švedski sto i javiš se na vreme." },
      steps: [
        {
          type: "decide",
          prompt: { de: "Du wachst mit Durchfall auf und sollst um sechs das Buffet betreuen. Was tust du?",
                    en: "You wake up with diarrhoea and are due to run the buffet at six. What do you do?",
                    pl: "Budzisz się z biegunką, a o szóstej masz obsługiwać bufet. Co robisz?",
                    hr: "Probudiš se s proljevom, a u šest trebaš raditi na švedskom stolu. Što ćeš učiniti?",
                    sr: "Probudiš se sa prolivom, a u šest treba da radiš na švedskom stolu. Šta ćeš uraditi?" },
          options: [
            { de: "Hingehen, Handschuhe anziehen und arbeiten", en: "Go in, put on gloves and work",
              pl: "Iść, założyć rękawiczki i pracować", hr: "Otići, staviti rukavice i raditi",
              sr: "Otići, staviti rukavice i raditi" },
            { de: "Hingehen, aber nur Geschirr abräumen", en: "Go in, but only clear dishes",
              pl: "Iść, ale tylko sprzątać naczynia", hr: "Otići, ali samo raspremati posuđe",
              sr: "Otići, ali samo raspremati posuđe" },
            { de: "Sofort dem Vorgesetzten melden und nicht ans Buffet gehen",
              en: "Report it to your supervisor at once and stay away from the buffet",
              pl: "Od razu zgłosić przełożonemu i nie podchodzić do bufetu",
              hr: "Odmah javiti nadređenom i ne prilaziti stolu",
              sr: "Odmah javiti nadređenom i ne prilaziti stolu" },
            { de: "Abwarten, ob es bis sechs besser wird", en: "Wait and see if it gets better by six",
              pl: "Poczekać, czy do szóstej przejdzie", hr: "Pričekati hoće li do šest proći",
              sr: "Sačekati hoće li do šest proći" }
          ],
          answer: 2,
          explain: { de: "Bei Durchfall, Erbrechen oder Fieber darfst du nicht mit offenen Lebensmitteln arbeiten. Handschuhe helfen nicht — die Keime sitzen in dir, nicht auf der Hand.",
                     en: "With diarrhoea, vomiting or fever you must not work with unpackaged food. Gloves don't help — the germs are inside you, not on your hand.",
                     pl: "Przy biegunce, wymiotach lub gorączce nie wolno pracować przy odkrytej żywności. Rękawiczki nie pomogą — zarazki są w tobie, nie na dłoni.",
                     hr: "Kod proljeva, povraćanja ili vrućice ne smiješ raditi s otvorenom hranom. Rukavice ne pomažu — klice su u tebi, ne na ruci.",
                     sr: "Kod proliva, povraćanja ili groznice ne smeš raditi sa otvorenom hranom. Rukavice ne pomažu — klice su u tebi, ne na ruci." }
        }
      ] },
  ]
};

export const breakfastTasks = {
  id: "breakfast",
  name: { de: "Frühstück & Buffet", en: "Breakfast & buffet", pl: "Śniadanie i bufet",
          hr: "Doručak i švedski stol", sr: "Doručak i švedski sto" },
  tagline: { de: "Buffet aufbauen, nachfüllen, sauber halten",
             en: "Set up, refill and keep the buffet clean",
             pl: "Ustawić bufet, uzupełniać, utrzymać czystość",
             hr: "Postaviti stol, nadopunjavati, održavati čistoću",
             sr: "Postaviti sto, dopunjavati, održavati čistoću" },
  accent: "#e8833a",
  icon: "UtensilsCrossed",
  blurb: { de: "Warm bleibt warm, kalt bleibt kalt — und jede Speise hat ihre eigene Zange.",
           en: "Hot stays hot, cold stays cold — and every dish has its own tongs.",
           pl: "Ciepłe zostaje ciepłe, zimne zimne — a każda potrawa ma własne szczypce.",
           hr: "Toplo ostaje toplo, hladno hladno — i svako jelo ima svoju hvataljku.",
           sr: "Toplo ostaje toplo, hladno hladno — i svako jelo ima svoju hvataljku." },
  tasks: [buffetAufbau, nachfuellenHygiene]
};
