/**
 * Öffentliche Bereiche — Handgriffe, fuenfsprachig.
 *
 * Abgrenzung: Housekeeping macht die Gaestezimmer. Diese Rolle macht alles
 * ausserhalb davon — Lobby, Gaenge, Stiegenhaus, Aufzug, Glastueren,
 * Wellness und WC-Anlagen. Dort sind immer Gaeste anwesend, und genau das
 * ist der Unterschied im Handgriff.
 *
 * Sprachen: de (Grundsprache), en, pl, hr, sr
 * Kroatisch und Serbisch sind eng verwandt; wo sich die Woerter wirklich
 * unterscheiden, ist das beruecksichtigt (točno/tačno, tko/ko, što/šta,
 * dizalo/lift, stubište/stepenište, suho/suvo, kabel/kabl).
 * Serbisch in lateinischer Schrift.
 */

const nassWischen = {
  id: "cl-nass",
  title: { de: "Nass wischen, wenn Gäste da sind", en: "Wet mopping with guests around",
           pl: "Mycie na mokro, gdy są goście",
           hr: "Mokro čišćenje kad su gosti prisutni", sr: "Mokro čišćenje kad su gosti prisutni" },
  goal: { de: "Du wischst einen Gang nass, ohne dass jemand ausrutscht oder stehen bleibt.",
          en: "You wet mop a corridor without anyone slipping or getting stuck.",
          pl: "Myjesz korytarz na mokro tak, że nikt się nie poślizgnie ani nie utknie.",
          hr: "Mokro očistiš hodnik tako da nitko ne poklizne i ne zapne.",
          sr: "Mokro očistiš hodnik tako da niko ne poklizne i ne zapne." },
  minutes: 4,
  stages: [
    { id: "cl-nass-s1",
      goal: { de: "Du siehst die vier Handgriffe und erkennst, wann das Warnschild stehen muss.",
              en: "You see the four moves and recognise when the warning sign has to be standing.",
              pl: "Widzisz cztery kroki i rozpoznajesz, kiedy musi stać tabliczka ostrzegawcza.",
              hr: "Vidiš četiri koraka i prepoznaješ kada znak upozorenja mora stajati.",
              sr: "Vidiš četiri koraka i prepoznaješ kada znak upozorenja mora da stoji." },
      steps: [
        {
          type: "demo",
          scene: "lobby",
          title: { de: "Schau dir den Ablauf an", en: "Watch the sequence", pl: "Obejrzyj przebieg",
                   hr: "Pogledaj postupak", sr: "Pogledaj postupak" },
          intro: { de: "Vier Handgriffe. Der wichtigste ist das Schild — und der Zeitpunkt, zu dem es steht.",
                   en: "Four moves. The sign is the important one — and when it goes up.",
                   pl: "Cztery ruchy. Najważniejszy jest znak — i moment, w którym stoi.",
                   hr: "Četiri pokreta. Najvažniji je znak — i trenutak kad stoji.",
                   sr: "Četiri pokreta. Najvažniji je znak — i trenutak kad stoji." },
          frames: [
            { caption: { de: "Wagen an die Wand stellen", en: "Park the trolley against the wall",
                         pl: "Ustaw wózek przy ścianie",
                         hr: "Postavi kolica uz zid", sr: "Postavi kolica uz zid" },
              detail: { de: "Wagen und Mopp gehören an die Wand, nie in die Mitte. Ein Gast mit Koffer muss vorbeikommen, ohne auszuweichen.",
                        en: "Trolley and mop belong against the wall, never in the middle. A guest with a suitcase must get past without detouring.",
                        pl: "Wózek i mop przy ścianie, nigdy na środku. Gość z walizką musi przejść bez omijania.",
                        hr: "Kolica i mop idu uz zid, nikad na sredinu. Gost s koferom mora proći bez zaobilaženja.",
                        sr: "Kolica i mop idu uz zid, nikad na sredinu. Gost sa koferom mora da prođe bez zaobilaženja." } },
            { caption: { de: "Die nasse Fläche planen", en: "Plan the wet area", pl: "Zaplanuj mokrą powierzchnię",
                         hr: "Isplaniraj mokru površinu", sr: "Isplaniraj mokru površinu" },
              detail: { de: "Schau zuerst an, welcher Bereich nass wird. Nasser Stein ist rutschig wie Eis — und man sieht es aus drei Metern nicht.",
                        en: "First look at which area will get wet. Wet stone is as slippery as ice — and you can't see it from three metres away.",
                        pl: "Najpierw spójrz, który obszar będzie mokry. Mokry kamień jest śliski jak lód — i z trzech metrów tego nie widać.",
                        hr: "Prvo pogledaj koje će područje biti mokro. Mokar kamen klizav je kao led — a s tri metra se to ne vidi.",
                        sr: "Prvo pogledaj koje će područje biti mokro. Mokar kamen je klizav kao led — a sa tri metra se to ne vidi." } },
            { caption: { de: "Warnschild aufstellen — vor dem Wischen", en: "Put up the warning sign — before mopping",
                         pl: "Postaw znak ostrzegawczy — przed myciem",
                         hr: "Postavi znak upozorenja — prije čišćenja", sr: "Postavi znak upozorenja — pre čišćenja" },
              detail: { de: "Das Schild steht, bevor der Mopp den Boden berührt. Stell es so, dass man es aus beiden Richtungen sieht.",
                        en: "The sign is up before the mop touches the floor. Place it so it is visible from both directions.",
                        pl: "Znak stoi, zanim mop dotknie podłogi. Ustaw go tak, by było go widać z obu stron.",
                        hr: "Znak stoji prije nego mop dotakne pod. Postavi ga tako da se vidi iz oba smjera.",
                        sr: "Znak stoji pre nego mop dotakne pod. Postavi ga tako da se vidi iz oba smera." } },
            { caption: { de: "Halbseitig wischen, Schild bleibt stehen", en: "Mop half the width, sign stays up",
                         pl: "Myj połowę szerokości, znak zostaje",
                         hr: "Čisti polovicu širine, znak ostaje", sr: "Čisti polovinu širine, znak ostaje" },
              detail: { de: "Immer nur eine Hälfte des Gangs wischen, die andere bleibt als Weg frei. Das Schild kommt erst weg, wenn der Boden trocken ist.",
                        en: "Always mop only one half of the corridor, the other stays open as a path. The sign only comes away once the floor is dry.",
                        pl: "Zawsze myj tylko połowę korytarza, druga zostaje jako przejście. Znak zabierasz dopiero, gdy podłoga jest sucha.",
                        hr: "Uvijek čisti samo polovicu hodnika, druga ostaje kao prolaz. Znak makni tek kad je pod suh.",
                        sr: "Uvek čisti samo polovinu hodnika, druga ostaje kao prolaz. Znak skloni tek kad je pod suv." } }
          ]
        },
      ] },
    { id: "cl-nass-s2",
      goal: { de: "Du bringst die Handgriffe beim nassen Wischen in die richtige Reihenfolge.",
              en: "You put the moves for wet mopping in the right order.",
              pl: "Układasz kroki mycia na mokro we właściwej kolejności.",
              hr: "Slažeš korake mokrog čišćenja pravilnim redoslijedom.",
              sr: "Slažeš korake mokrog čišćenja pravilnim redosledom." },
      steps: [
        {
          type: "sequence",
          prompt: { de: "Jetzt du — in welcher Reihenfolge?", en: "Now you — in what order?",
                    pl: "Teraz ty — w jakiej kolejności?",
                    hr: "Sada ti — kojim redoslijedom?", sr: "Sada ti — kojim redosledom?" },
      steps: [
            { de: "Wagen an die Wand stellen", en: "Park the trolley against the wall", pl: "Ustaw wózek przy ścianie",
              hr: "Postavi kolica uz zid", sr: "Postavi kolica uz zid" },
            { de: "Warnschild aufstellen", en: "Put up the warning sign", pl: "Postaw znak ostrzegawczy",
              hr: "Postavi znak upozorenja", sr: "Postavi znak upozorenja" },
            { de: "Erste Hälfte wischen", en: "Mop the first half", pl: "Umyj pierwszą połowę",
              hr: "Očisti prvu polovicu", sr: "Očisti prvu polovinu" },
            { de: "Zweite Hälfte wischen, wenn die erste trocken ist", en: "Mop the second half once the first is dry",
              pl: "Umyj drugą połowę, gdy pierwsza wyschnie",
              hr: "Očisti drugu polovicu kad je prva suha", sr: "Očisti drugu polovinu kad je prva suva" },
            { de: "Schild wegräumen, wenn alles trocken ist", en: "Take the sign away once everything is dry",
              pl: "Zabierz znak, gdy wszystko jest suche",
              hr: "Makni znak kad je sve suho", sr: "Skloni znak kad je sve suvo" }
          ],
          explain: { de: "Halbseitig wischen dauert länger, aber niemand muss über den nassen Teil gehen. Ein gesperrter Gang ist im Hotel keine Option.",
                     en: "Mopping half at a time takes longer, but nobody has to cross the wet part. A blocked corridor is not an option in a hotel.",
                     pl: "Mycie połowami trwa dłużej, ale nikt nie musi wchodzić na mokrą część. Zamknięty korytarz w hotelu nie wchodzi w grę.",
                     hr: "Čišćenje po polovicama traje dulje, ali nitko ne mora prijeći preko mokrog dijela. Zatvoren hodnik u hotelu nije opcija.",
                     sr: "Čišćenje po polovinama traje duže, ali niko ne mora da pređe preko mokrog dela. Zatvoren hodnik u hotelu nije opcija." }
        },
      ] },
    { id: "cl-nass-s3",
      goal: { de: "Du lässt das Schild stehen, bis der Boden trocken ist, und weißt, was im Gästebereich sonst noch gilt.",
              en: "You leave the sign up until the floor is dry, and you know what else applies in the guest area.",
              pl: "Zostawiasz tabliczkę, dopóki podłoga nie wyschnie, i wiesz, co jeszcze obowiązuje w strefie gości.",
              hr: "Ostavljaš znak dok pod ne bude suh i znaš što još vrijedi u prostoru za goste.",
              sr: "Ostavljaš znak dok pod ne bude suv i znaš šta još važi u prostoru za goste." },
      steps: [
        {
          type: "decide",
          prompt: { de: "Du bist mit dem Wischen fertig, der Boden ist noch feucht. Du musst frisches Wasser holen. Was tust du mit dem Schild?",
                    en: "You have finished mopping, the floor is still damp. You need to fetch fresh water. What do you do with the sign?",
                    pl: "Skończyłeś myć, podłoga jest jeszcze wilgotna. Musisz przynieść świeżą wodę. Co robisz ze znakiem?",
                    hr: "Završio si s čišćenjem, pod je još vlažan. Moraš po svježu vodu. Što ćeš sa znakom?",
                    sr: "Završio si sa čišćenjem, pod je još vlažan. Moraš po svežu vodu. Šta ćeš sa znakom?" },
          options: [
            { de: "Mitnehmen, du bist ja gleich zurück", en: "Take it with you, you'll be right back",
              pl: "Zabrać ze sobą, zaraz wracasz",
              hr: "Ponijeti sa sobom, odmah se vraćaš", sr: "Poneti sa sobom, odmah se vraćaš" },
            { de: "An die Wand lehnen, damit es nicht stört", en: "Lean it against the wall so it's out of the way",
              pl: "Oprzeć o ścianę, żeby nie przeszkadzał",
              hr: "Nasloniti na zid da ne smeta", sr: "Nasloniti na zid da ne smeta" },
            { de: "Stehen lassen, bis der Boden wirklich trocken ist", en: "Leave it standing until the floor is really dry",
              pl: "Zostawić, aż podłoga naprawdę wyschnie",
              hr: "Ostaviti dok pod stvarno ne bude suh", sr: "Ostaviti dok pod stvarno ne bude suv" },
            { de: "Einem Gast sagen, er soll aufpassen", en: "Tell a guest to watch out",
              pl: "Powiedzieć gościowi, żeby uważał",
              hr: "Reći gostu neka pazi", sr: "Reći gostu neka pazi" }
          ],
          answer: 2,
          explain: { de: "Feucht ist genauso rutschig wie nass. Solange du weg bist, ist das Schild die einzige Warnung — ein gestürzter Gast ist ein Versicherungsfall für das Haus.",
                     en: "Damp is just as slippery as wet. While you are away the sign is the only warning — a guest who falls becomes an insurance case for the hotel.",
                     pl: "Wilgotne jest równie śliskie jak mokre. Gdy cię nie ma, znak jest jedynym ostrzeżeniem — upadek gościa to sprawa ubezpieczeniowa hotelu.",
                     hr: "Vlažno je jednako klizavo kao mokro. Dok tebe nema, znak je jedino upozorenje — pad gosta je za kuću slučaj za osiguranje.",
                     sr: "Vlažno je isto tako klizavo kao mokro. Dok tebe nema, znak je jedino upozorenje — pad gosta je za kuću slučaj za osiguranje." }
        },
        {
          type: "checklist",
          prompt: { de: "Was gehört zum nassen Wischen im Gästebereich? Wähle alles Richtige.",
                    en: "What belongs to wet mopping in a guest area? Select everything correct.",
                    pl: "Co należy do mycia na mokro w strefie gości? Zaznacz wszystko poprawne.",
                    hr: "Što spada u mokro čišćenje u prostoru za goste? Odaberi sve točno.",
                    sr: "Šta spada u mokro čišćenje u prostoru za goste? Izaberi sve tačno." },
          items: [
            { label: { de: "Schild steht, bevor der erste Zug gemacht wird", en: "Sign is up before the first stroke",
                       pl: "Znak stoi przed pierwszym pociągnięciem",
                       hr: "Znak stoji prije prvog poteza", sr: "Znak stoji pre prvog poteza" }, correct: true },
            { label: { de: "Immer ein trockener Weg bleibt frei", en: "A dry path always stays open",
                       pl: "Zawsze zostaje wolne suche przejście",
                       hr: "Uvijek ostaje slobodan suh prolaz", sr: "Uvek ostaje slobodan suv prolaz" }, correct: true },
            { label: { de: "Mopp gut ausgewrungen, keine Pfützen", en: "Mop wrung out well, no puddles",
                       pl: "Mop dobrze wyciśnięty, bez kałuż",
                       hr: "Mop dobro ocijeđen, bez lokvi", sr: "Mop dobro isceđen, bez lokvi" }, correct: true },
            { label: { de: "Schild sofort nach dem letzten Zug wegräumen", en: "Sign put away right after the last stroke",
                       pl: "Znak zabrany zaraz po ostatnim pociągnięciu",
                       hr: "Znak maknut odmah nakon zadnjeg poteza", sr: "Znak sklonjen odmah posle poslednjeg poteza" }, correct: false },
            { label: { de: "Den ganzen Gang auf einmal nass machen", en: "Wetting the whole corridor at once",
                       pl: "Zmoczenie całego korytarza naraz",
                       hr: "Namočiti cijeli hodnik odjednom", sr: "Nakvasiti ceo hodnik odjednom" }, correct: false },
            { label: { de: "Den Zugang zum Aufzug mit dem Wagen absperren", en: "Blocking the lift access with the trolley",
                       pl: "Zastawienie dojścia do windy wózkiem",
                       hr: "Zapriječiti prilaz dizalu kolicima", sr: "Zakrčiti prilaz liftu kolicima" }, correct: false }
          ],
          explain: { de: "Ein zu früh weggeräumtes Schild ist gefährlicher als gar keines: Der Gast glaubt, der Boden sei trocken.",
                     en: "A sign taken away too early is more dangerous than none at all: the guest believes the floor is dry.",
                     pl: "Zbyt wcześnie zabrany znak jest groźniejszy niż żaden: gość myśli, że podłoga jest sucha.",
                     hr: "Prerano maknut znak opasniji je od nikakvog: gost misli da je pod suh.",
                     sr: "Prerano sklonjen znak opasniji je od nikakvog: gost misli da je pod suv." }
        }
      ] },
  ]
};

const arbeitenVorGaesten = {
  id: "cl-gast",
  title: { de: "Arbeiten vor Gästen", en: "Working in front of guests", pl: "Praca na oczach gości",
           hr: "Rad pred gostima", sr: "Rad pred gostima" },
  goal: { de: "Du arbeitest in Lobby, Gang und Stiegenhaus, ohne dass ein Gast gestört wird.",
          en: "You work in the lobby, corridor and stairwell without disturbing a guest.",
          pl: "Pracujesz w lobby, na korytarzu i klatce schodowej, nie przeszkadzając gościom.",
          hr: "Radiš u predvorju, hodniku i na stubištu, a da gost ne bude ometen.",
          sr: "Radiš u holu, hodniku i na stepeništu, a da gost ne bude ometen." },
  minutes: 5,
  stages: [
    { id: "cl-gast-s1",
      goal: { de: "Du gibst dem Gast im Gang Vorrang und unterbrichst deine Arbeit in der richtigen Reihenfolge.",
              en: "You give the guest priority in the corridor and interrupt your work in the right order.",
              pl: "Dajesz gościowi pierwszeństwo na korytarzu i przerywasz pracę we właściwej kolejności.",
              hr: "Daješ gostu prednost u hodniku i prekidaš svoj rad pravilnim redoslijedom.",
              sr: "Daješ gostu prednost u hodniku i prekidaš svoj rad pravilnim redosledom." },
      steps: [
        {
          type: "sequence",
          prompt: { de: "Du saugst den Gang. Ein Gast kommt dir entgegen. In welcher Reihenfolge?",
                    en: "You are vacuuming the corridor. A guest comes towards you. In what order?",
                    pl: "Odkurzasz korytarz. Naprzeciw idzie gość. W jakiej kolejności?",
                    hr: "Usisavaš hodnik. Gost ti dolazi u susret. Kojim redoslijedom?",
                    sr: "Usisavaš hodnik. Gost ti dolazi u susret. Kojim redosledom?" },
      steps: [
            { de: "Gerät ausschalten", en: "Switch the machine off", pl: "Wyłącz urządzenie",
              hr: "Isključi uređaj", sr: "Isključi uređaj" },
            { de: "Wagen und Kabel zur Seite räumen", en: "Move trolley and cable aside",
              pl: "Odsuń wózek i kabel na bok",
              hr: "Makni kolica i kabel u stranu", sr: "Skloni kolica i kabl u stranu" },
            { de: "Grüßen und Platz machen", en: "Greet and make room", pl: "Przywitaj się i zrób miejsce",
              hr: "Pozdravi i napravi mjesta", sr: "Pozdravi i napravi mesta" },
            { de: "Gast vorbeigehen lassen", en: "Let the guest pass", pl: "Przepuść gościa",
              hr: "Pusti gosta da prođe", sr: "Pusti gosta da prođe" },
            { de: "Erst dann weiterarbeiten", en: "Only then carry on working", pl: "Dopiero potem pracuj dalej",
              hr: "Tek onda nastavi raditi", sr: "Tek onda nastavi da radiš" }
          ],
          explain: { de: "Der Gast hat immer Vorrang. Ausschalten kommt zuerst, weil du sonst nicht hörst, ob er dich etwas fragt.",
                     en: "The guest always has priority. Switching off comes first, otherwise you can't hear if he asks you something.",
                     pl: "Gość ma zawsze pierwszeństwo. Wyłączenie jest pierwsze, bo inaczej nie usłyszysz, gdy o coś zapyta.",
                     hr: "Gost uvijek ima prednost. Isključivanje je prvo jer inače ne čuješ ako te nešto pita.",
                     sr: "Gost uvek ima prednost. Isključivanje je prvo jer inače ne čuješ ako te nešto pita." }
        },
      ] },
    { id: "cl-gast-s2",
      goal: { de: "Du bleibst für Gäste ansprechbar, auch wenn du die Frage nicht ganz verstehst, und hältst Wege und Aufzug frei.",
              en: "You stay approachable for guests even when you do not fully understand the question, and keep paths and the lift clear.",
              pl: "Pozostajesz dostępny dla gości, nawet gdy nie rozumiesz pytania do końca, i utrzymujesz drogi i windę wolne.",
              hr: "Ostaješ dostupan gostima i kad pitanje ne razumiješ do kraja te držiš putove i dizalo slobodnima.",
              sr: "Ostaješ dostupan gostima i kad pitanje ne razumeš do kraja i držiš puteve i lift slobodnima." },
      steps: [
        {
          type: "decide",
          prompt: { de: "Ein Gast fragt dich im Gang, wo der Wellnessbereich ist. Du verstehst die Frage nur halb. Was tust du?",
                    en: "A guest asks you in the corridor where the spa is. You only half understand the question. What do you do?",
                    pl: "Gość pyta cię na korytarzu, gdzie jest strefa wellness. Rozumiesz pytanie tylko w połowie. Co robisz?",
                    hr: "Gost te u hodniku pita gdje je wellness. Razumiješ pitanje samo napola. Što ćeš učiniti?",
                    sr: "Gost te u hodniku pita gde je wellness. Razumeš pitanje samo napola. Šta ćeš uraditi?" },
          options: [
            { de: "Achselzucken und weiterarbeiten", en: "Shrug and carry on working",
              pl: "Wzruszyć ramionami i pracować dalej",
              hr: "Slegnuti ramenima i nastaviti raditi", sr: "Slegnuti ramenima i nastaviti da radiš" },
            { de: "Irgendwohin zeigen, damit die Frage erledigt ist", en: "Point somewhere so the question is dealt with",
              pl: "Pokazać gdzieś, żeby mieć pytanie z głowy",
              hr: "Pokazati nekamo da pitanje bude riješeno", sr: "Pokazati negde da pitanje bude rešeno" },
            { de: "Freundlich grüßen und den Gast zur Rezeption begleiten", en: "Greet warmly and walk the guest to reception",
              pl: "Uprzejmie przywitać i odprowadzić gościa do recepcji",
              hr: "Ljubazno pozdraviti i otpratiti gosta do recepcije", sr: "Ljubazno pozdraviti i otpratiti gosta do recepcije" },
            { de: "Sagen, dass du kein Deutsch sprichst, und weggehen", en: "Say you don't speak German and walk away",
              pl: "Powiedzieć, że nie mówisz po niemiecku, i odejść",
              hr: "Reći da ne govoriš njemački i otići", sr: "Reći da ne govoriš nemački i otići" }
          ],
          answer: 2,
          explain: { de: "Begleiten geht immer, auch ohne Sprache. Ein falsch gezeigter Weg schickt den Gast durchs halbe Haus und kommt als Beschwerde zurück.",
                     en: "Walking someone there always works, even without a shared language. A wrongly pointed direction sends the guest across half the hotel and comes back as a complaint.",
                     pl: "Odprowadzenie działa zawsze, nawet bez wspólnego języka. Źle wskazana droga wyśle gościa przez pół hotelu i wróci jako skarga.",
                     hr: "Otpratiti se može uvijek, i bez zajedničkog jezika. Krivo pokazan put pošalje gosta kroz pola kuće i vrati se kao pritužba.",
                     sr: "Otpratiti se može uvek, i bez zajedničkog jezika. Pogrešno pokazan put pošalje gosta kroz pola kuće i vrati se kao žalba." }
        },
        {
          type: "checklist",
          prompt: { de: "Was gilt beim Arbeiten in Lobby, Stiegenhaus und Aufzug? Wähle alles Richtige.",
                    en: "What applies when working in lobby, stairwell and lift? Select everything correct.",
                    pl: "Co obowiązuje przy pracy w lobby, na klatce schodowej i w windzie? Zaznacz wszystko poprawne.",
                    hr: "Što vrijedi pri radu u predvorju, na stubištu i u dizalu? Odaberi sve točno.",
                    sr: "Šta važi pri radu u holu, na stepeništu i u liftu? Izaberi sve tačno." },
          items: [
            { label: { de: "Jeden Gast grüßen — „Grüß Gott\" reicht", en: "Greet every guest — a simple hello is enough",
                       pl: "Przywitać każdego gościa — wystarczy „dzień dobry\"",
                       hr: "Pozdraviti svakog gosta — dovoljan je „dobar dan\"",
                       sr: "Pozdraviti svakog gosta — dovoljan je „dobar dan\"" }, correct: true },
            { label: { de: "Laute Geräte nur in ruhigen Zeiten nach Hausvorgabe", en: "Loud machines only in quiet periods as the house specifies",
                       pl: "Głośne urządzenia tylko w spokojnych porach według zasad hotelu",
                       hr: "Glasni uređaji samo u mirnim razdobljima prema pravilu kuće",
                       sr: "Glasni uređaji samo u mirnim periodima prema pravilu kuće" }, correct: true },
            { label: { de: "Kabel an der Wand entlang, nie quer über den Gang", en: "Cable along the wall, never across the corridor",
                       pl: "Kabel wzdłuż ściany, nigdy w poprzek korytarza",
                       hr: "Kabel uz zid, nikad poprijeko preko hodnika",
                       sr: "Kabl uz zid, nikad popreko preko hodnika" }, correct: true },
            { label: { de: "Fluchtwege und Brandschutztüren bleiben frei", en: "Escape routes and fire doors stay clear",
                       pl: "Drogi ewakuacyjne i drzwi przeciwpożarowe zostają wolne",
                       hr: "Evakuacijski putovi i protupožarna vrata ostaju slobodni",
                       sr: "Evakuacioni putevi i protivpožarna vrata ostaju slobodni" }, correct: true },
            { label: { de: "Den Wagen kurz vor die Brandschutztür stellen", en: "Parking the trolley briefly in front of the fire door",
                       pl: "Postawienie wózka na chwilę przed drzwiami przeciwpożarowymi",
                       hr: "Staviti kolica nakratko pred protupožarna vrata",
                       sr: "Staviti kolica nakratko pred protivpožarna vrata" }, correct: false },
            { label: { de: "Den Aufzug mit dem Wagen blockieren, bis du fertig bist", en: "Blocking the lift with the trolley until you are done",
                       pl: "Blokowanie windy wózkiem, aż skończysz",
                       hr: "Blokirati dizalo kolicima dok ne završiš",
                       sr: "Blokirati lift kolicima dok ne završiš" }, correct: false },
            { label: { de: "Im Gespräch über andere Gäste sprechen", en: "Talking about other guests where you can be heard",
                       pl: "Rozmawianie o innych gościach tam, gdzie słychać",
                       hr: "Razgovarati o drugim gostima gdje se čuje",
                       sr: "Razgovarati o drugim gostima gde se čuje" }, correct: false }
          ],
          explain: { de: "Ein Wagen vor einer Brandschutztür ist auch für fünf Minuten verboten — im Ernstfall entscheidet genau diese Tür.",
                     en: "A trolley in front of a fire door is forbidden even for five minutes — in an emergency that very door decides things.",
                     pl: "Wózek przed drzwiami przeciwpożarowymi jest zabroniony nawet na pięć minut — w razie pożaru decydują właśnie te drzwi.",
                     hr: "Kolica pred protupožarnim vratima zabranjena su i na pet minuta — u hitnom slučaju upravo ta vrata odlučuju.",
                     sr: "Kolica pred protivpožarnim vratima zabranjena su i na pet minuta — u hitnom slučaju upravo ta vrata odlučuju." }
        },
      ] },
    { id: "cl-gast-s3",
      goal: { de: "Du sicherst eine Gefahrenstelle zuerst und räumst sie erst danach weg.",
              en: "You secure a hazard first and only then clear it up.",
              pl: "Najpierw zabezpieczasz niebezpieczne miejsce, a dopiero potem je sprzątasz.",
              hr: "Prvo osiguraš opasno mjesto, a tek onda ga raspremiš.",
              sr: "Prvo osiguraš opasno mesto, a tek onda ga raspremiš." },
      steps: [
        {
          type: "decide",
          prompt: { de: "In der Lobby fällt ein Glas zu Boden und zerspringt. Gäste sitzen daneben. Was tust du zuerst?",
                    en: "A glass falls and shatters in the lobby. Guests are sitting next to it. What do you do first?",
                    pl: "W lobby spada szklanka i rozbija się. Obok siedzą goście. Co robisz najpierw?",
                    hr: "U predvorju padne čaša i razbije se. Gosti sjede pokraj. Što ćeš prvo?",
                    sr: "U holu padne čaša i razbije se. Gosti sede pored. Šta ćeš prvo?" },
          options: [
            { de: "Besen holen, das dauert ja nur einen Moment", en: "Fetch a broom, it only takes a moment",
              pl: "Przynieść miotłę, to chwila",
              hr: "Otići po metlu, to traje samo trenutak", sr: "Otići po metlu, to traje samo trenutak" },
            { de: "Bei den Scherben stehen bleiben und sie absichern, bis Hilfe da ist",
              en: "Stay with the shards and secure the spot until help arrives",
              pl: "Zostać przy odłamkach i zabezpieczyć miejsce, aż przyjdzie pomoc",
              hr: "Ostati kod krhotina i osigurati mjesto dok ne dođe pomoć",
              sr: "Ostati kod krhotina i obezbediti mesto dok ne dođe pomoć" },
            { de: "Die größten Stücke schnell mit der Hand aufheben", en: "Quickly pick up the biggest pieces by hand",
              pl: "Szybko podnieść największe kawałki ręką",
              hr: "Brzo rukom podignuti najveće komade", sr: "Brzo rukom podignuti najveće komade" },
            { de: "Einen Kollegen suchen gehen", en: "Go and look for a colleague", pl: "Pójść poszukać kolegi",
              hr: "Otići potražiti kolegu", sr: "Otići da potražiš kolegu" }
          ],
          answer: 1,
          explain: { de: "Scherben springen weit und man sieht sie kaum. Wer die Stelle verlässt, überlässt sie dem nächsten Gast in Sandalen — sichern geht vor aufkehren.",
                     en: "Shards fly far and are hard to see. Leave the spot and you hand it to the next guest in sandals — securing comes before sweeping.",
                     pl: "Odłamki lecą daleko i ledwo je widać. Kto odejdzie, zostawia je następnemu gościowi w sandałach — zabezpieczenie przed zamiataniem.",
                     hr: "Krhotine odlete daleko i jedva se vide. Tko napusti mjesto, prepušta ga sljedećem gostu u sandalama — osiguranje ide prije metenja.",
                     sr: "Krhotine odlete daleko i jedva se vide. Ko napusti mesto, prepušta ga sledećem gostu u sandalama — obezbeđenje ide pre metenja." }
        }
      ] },
  ]
};

export const cleaningTasks = {
  id: "cleaning",
  name: { de: "Öffentliche Bereiche", en: "Public areas", pl: "Strefy publiczne",
          hr: "Javni prostori", sr: "Javni prostori" },
  tagline: { de: "Sauber machen, wo Gäste unterwegs sind", en: "Cleaning where guests are on the move",
             pl: "Sprzątanie tam, gdzie chodzą goście",
             hr: "Čišćenje ondje gdje se gosti kreću", sr: "Čišćenje tamo gde se gosti kreću" },
  accent: "#0f9b8e",
  icon: "SprayCan",
  blurb: { de: "Lobby, Gang, Stiegenhaus und Aufzug — außerhalb der Zimmer schaut immer jemand zu.",
           en: "Lobby, corridor, stairwell and lift — outside the rooms someone is always watching.",
           pl: "Lobby, korytarz, klatka schodowa i winda — poza pokojami zawsze ktoś patrzy.",
           hr: "Predvorje, hodnik, stubište i dizalo — izvan soba uvijek netko gleda.",
           sr: "Hol, hodnik, stepenište i lift — izvan soba uvek neko gleda." },
  tasks: [nassWischen, arbeitenVorGaesten]
};
