/**
 * Housekeeping — vier weitere Handgriffe, fuenfsprachig.
 *
 * Sprachen: de (Grundsprache), en, pl, hr, sr — Serbisch in lateinischer Schrift.
 * Wo sich Kroatisch und Serbisch wirklich unterscheiden, ist das beruecksichtigt
 * (kupaonica/kupatilo, ručnik/peškir, madrac/dušek, plahta/čaršav, ladica/fioka,
 * točno/tačno, tko/ko, što/šta).
 */

const badReinigen = {
  id: "hk-bad",
  title: { de: "Bad reinigen", en: "Cleaning the bathroom", pl: "Sprzątanie łazienki",
           hr: "Čišćenje kupaonice", sr: "Čišćenje kupatila" },
  goal: { de: "Du reinigst das Bad in der richtigen Reihenfolge — ohne Keime zu verschleppen.",
          en: "You clean the bathroom in the right order — without spreading germs.",
          pl: "Sprzątasz łazienkę we właściwej kolejności — bez roznoszenia zarazków.",
          hr: "Čistiš kupaonicu ispravnim redoslijedom — bez prenošenja klica.",
          sr: "Čistiš kupatilo ispravnim redosledom — bez prenošenja klica." },
  minutes: 6,
  stages: [
    {
      id: "hk-bad-s1",
      goal: { de: "Du siehst, warum das Bad von oben nach unten gereinigt wird und das WC zuletzt kommt.",
              en: "You see why the bathroom is cleaned top to bottom and the toilet comes last.",
              pl: "Widzisz, dlaczego łazienkę sprząta się od góry do dołu, a WC na końcu.",
              hr: "Vidiš zašto se kupaonica čisti odozgo prema dolje i zašto WC ide zadnji.",
              sr: "Vidiš zašto se kupatilo čisti odozgo nadole i zašto WC ide poslednji." },
      steps: [
        {
          type: "demo",
          scene: "bath",
          title: { de: "Schau dir die Reihenfolge an", en: "Watch the order", pl: "Obejrzyj kolejność",
                   hr: "Pogledaj redoslijed", sr: "Pogledaj redosled" },
          intro: { de: "Vier Zonen, immer dieselbe Richtung: vom Saubersten zum Schmutzigsten. Das WC kommt zuletzt.",
                   en: "Four zones, always the same direction: from the cleanest to the dirtiest. The toilet comes last.",
                   pl: "Cztery strefy, zawsze ten sam kierunek: od najczystszego do najbrudniejszego. WC na końcu.",
                   hr: "Četiri zone, uvijek isti smjer: od najčišćeg prema najprljavijem. WC ide zadnji.",
                   sr: "Četiri zone, uvek isti smer: od najčistijeg prema najprljavijem. WC ide poslednji." },
          frames: [
            { caption: { de: "1. Spiegel", en: "1. Mirror", pl: "1. Lustro", hr: "1. Ogledalo", sr: "1. Ogledalo" },
              detail: { de: "Ganz oben anfangen: Spiegel und Glas mit dem blauen Tuch. Tropfen fallen nach unten — was du später putzt, machst du nicht zweimal.",
                        en: "Start at the top: mirror and glass with the blue cloth. Drops fall downwards — what you clean later, you don't clean twice.",
                        pl: "Zacznij od góry: lustro i szkło niebieską ściereczką. Krople spadają w dół — tego, co czyścisz później, nie robisz dwa razy.",
                        hr: "Počni gore: ogledalo i staklo plavom krpom. Kapi padaju prema dolje — ono što čistiš poslije, ne čistiš dvaput.",
                        sr: "Počni gore: ogledalo i staklo plavom krpom. Kapi padaju nadole — ono što čistiš kasnije, ne čistiš dvaput." } },
            { caption: { de: "2. Waschbecken", en: "2. Washbasin", pl: "2. Umywalka", hr: "2. Umivaonik", sr: "2. Lavabo" },
              detail: { de: "Mittel aufsprühen, kurz einwirken lassen, dann Becken, Armatur und Ablage wischen. Zahnpastaspritzer sieht jeder Gast sofort.",
                        en: "Spray the product, let it work briefly, then wipe basin, tap and shelf. Every guest spots toothpaste splashes at once.",
                        pl: "Spryskaj środkiem, poczekaj chwilę, potem wytrzyj umywalkę, baterię i półkę. Ślady pasty do zębów gość widzi od razu.",
                        hr: "Poprskaj sredstvom, pusti da kratko djeluje, pa obriši umivaonik, slavinu i policu. Mrlje od paste za zube gost odmah vidi.",
                        sr: "Poprskaj sredstvom, pusti da kratko deluje, pa obriši lavabo, slavinu i policu. Mrlje od paste za zube gost odmah vidi." } },
            { caption: { de: "3. Dusche", en: "3. Shower", pl: "3. Prysznic", hr: "3. Tuš", sr: "3. Tuš" },
              detail: { de: "Kalkmittel auf Wand und Glas, einwirken lassen, dann von oben nach unten abziehen. Den Abfluss nicht vergessen — Haare dort sind die häufigste Beschwerde.",
                        en: "Limescale remover on wall and glass, let it work, then squeegee from top to bottom. Don't forget the drain — hair there is the most common complaint.",
                        pl: "Środek na kamień na ścianę i szkło, poczekaj, potem ściągaj z góry na dół. Nie zapomnij o odpływie — włosy to najczęstsza skarga.",
                        hr: "Sredstvo za kamenac na zid i staklo, pusti da djeluje, pa povlači odozgo prema dolje. Ne zaboravi odvod — dlake su najčešća pritužba.",
                        sr: "Sredstvo za kamenac na zid i staklo, pusti da deluje, pa povlači odozgo nadole. Ne zaboravi odvod — dlake su najčešća žalba." } },
            { caption: { de: "4. WC — zuletzt", en: "4. Toilet — last", pl: "4. WC — na końcu",
                         hr: "4. WC — zadnji", sr: "4. WC — poslednji" },
              detail: { de: "Nur mit dem roten Tuch und nur hier. WC-Reiniger unter den Rand, einwirken lassen, dann Brille, Deckel und Spültaste. Danach Handschuhe wechseln.",
                        en: "Only with the red cloth and only here. Toilet cleaner under the rim, let it work, then seat, lid and flush button. Change gloves afterwards.",
                        pl: "Tylko czerwoną ściereczką i tylko tutaj. Środek pod obrzeże, poczekaj, potem deska, pokrywa i przycisk spłukiwania. Potem zmień rękawice.",
                        hr: "Samo crvenom krpom i samo ovdje. Sredstvo pod rub, pusti da djeluje, pa daska, poklopac i tipka vodokotlića. Nakon toga promijeni rukavice.",
                        sr: "Samo crvenom krpom i samo ovde. Sredstvo pod ivicu, pusti da deluje, pa daska, poklopac i dugme vodokotlića. Posle toga promeni rukavice." } },
            { caption: { de: "Fertig", en: "Done", pl: "Gotowe", hr: "Gotovo", sr: "Gotovo" },
              detail: { de: "Zum Schluss Boden von hinten zur Tür wischen, frische Handtücher auflegen und noch einmal von der Tür aus schauen.",
                        en: "Finally mop the floor from the back towards the door, put out fresh towels and take one last look from the door.",
                        pl: "Na koniec umyj podłogę od tyłu do drzwi, połóż świeże ręczniki i spójrz jeszcze raz od drzwi.",
                        hr: "Na kraju obriši pod od kraja prema vratima, stavi čiste ručnike i pogledaj još jednom s vrata.",
                        sr: "Na kraju obriši pod od kraja prema vratima, stavi čiste peškire i pogledaj još jednom sa vrata." } }
          ]
        }
      ]
    },
    {
      id: "hk-bad-s2",
      goal: { de: "Du hältst die Reihenfolge vom Saubersten zum Schmutzigsten ein und arbeitest nach dem WC nie mit demselben Tuch weiter.",
              en: "You keep the order from cleanest to dirtiest and never carry on with the same cloth after the toilet.",
              pl: "Zachowujesz kolejność od najczystszego do najbrudniejszego i po WC nigdy nie pracujesz dalej tą samą ściereczką.",
              hr: "Držiš se redoslijeda od najčišćeg prema najprljavijem i nakon WC-a nikad ne nastavljaš istom krpom.",
              sr: "Držiš se redosleda od najčistijeg prema najprljavijem i posle WC-a nikad ne nastavljaš istom krpom." },
      steps: [
        {
          type: "sequence",
          prompt: { de: "In welcher Reihenfolge reinigst du das Bad?",
                    en: "In what order do you clean the bathroom?",
                    pl: "W jakiej kolejności sprzątasz łazienkę?",
                    hr: "Kojim redoslijedom čistiš kupaonicu?",
                    sr: "Kojim redosledom čistiš kupatilo?" },
          steps: [
            { de: "Spiegel und Glas", en: "Mirror and glass", pl: "Lustro i szkło",
              hr: "Ogledalo i staklo", sr: "Ogledalo i staklo" },
            { de: "Waschbecken und Armatur", en: "Basin and tap", pl: "Umywalka i bateria",
              hr: "Umivaonik i slavina", sr: "Lavabo i slavina" },
            { de: "Dusche und Abfluss", en: "Shower and drain", pl: "Prysznic i odpływ",
              hr: "Tuš i odvod", sr: "Tuš i odvod" },
            { de: "WC mit dem roten Tuch", en: "Toilet with the red cloth", pl: "WC czerwoną ściereczką",
              hr: "WC crvenom krpom", sr: "WC crvenom krpom" },
            { de: "Boden zur Tür hin wischen", en: "Mop the floor towards the door", pl: "Umyj podłogę w stronę drzwi",
              hr: "Obriši pod prema vratima", sr: "Obriši pod prema vratima" },
            { de: "Frische Handtücher auflegen", en: "Put out fresh towels", pl: "Połóż świeże ręczniki",
              hr: "Stavi čiste ručnike", sr: "Stavi čiste peškire" }
          ],
          explain: { de: "Wer beim WC anfängt, trägt Keime auf Waschbecken und Spiegel. Die Reihenfolge ist der ganze Hygieneschutz.",
                     en: "Start at the toilet and you carry germs to the basin and the mirror. The order is the entire hygiene protection.",
                     pl: "Kto zaczyna od WC, roznosi zarazki na umywalkę i lustro. Kolejność to cała ochrona higieny.",
                     hr: "Tko počne od WC-a, prenosi klice na umivaonik i ogledalo. Redoslijed je cijela zaštita higijene.",
                     sr: "Ko počne od WC-a, prenosi klice na lavabo i ogledalo. Redosled je cela zaštita higijene." }
        },
        {
          type: "decide",
          prompt: { de: "Du hast das WC geputzt. Das Waschbecken hast du vergessen. Was tust du?",
                    en: "You've cleaned the toilet. You forgot the basin. What do you do?",
                    pl: "Umyłeś WC. Zapomniałeś o umywalce. Co robisz?",
                    hr: "Očistio si WC. Zaboravio si umivaonik. Što ćeš učiniti?",
                    sr: "Očistio si WC. Zaboravio si lavabo. Šta ćeš uraditi?" },
          options: [
            { de: "Mit demselben roten Tuch schnell das Becken nachwischen",
              en: "Quickly wipe the basin with the same red cloth",
              pl: "Szybko przetrzeć umywalkę tą samą czerwoną ściereczką",
              hr: "Brzo prebrisati umivaonik istom crvenom krpom",
              sr: "Brzo prebrisati lavabo istom crvenom krpom" },
            { de: "Handschuhe und Tuch wechseln, dann das Becken mit dem blauen Tuch machen",
              en: "Change gloves and cloth, then do the basin with the blue cloth",
              pl: "Zmienić rękawice i ściereczkę, potem umyć umywalkę niebieską",
              hr: "Promijeniti rukavice i krpu, pa umivaonik očistiti plavom krpom",
              sr: "Promeniti rukavice i krpu, pa lavabo očistiti plavom krpom" },
            { de: "Das Becken nur mit Wasser abspülen", en: "Just rinse the basin with water",
              pl: "Tylko spłukać umywalkę wodą", hr: "Samo isprati umivaonik vodom",
              sr: "Samo isprati lavabo vodom" },
            { de: "Weglassen — das Becken sieht sauber aus", en: "Skip it — the basin looks clean",
              pl: "Pominąć — umywalka wygląda czysto", hr: "Preskočiti — umivaonik izgleda čisto",
              sr: "Preskočiti — lavabo izgleda čisto" }
          ],
          answer: 1,
          explain: { de: "Das rote Tuch war am WC und gehört danach in die Wäsche. Farbtrennung ist genau dafür da: damit WC-Keime nie ans Waschbecken kommen.",
                     en: "The red cloth was on the toilet and goes to the laundry afterwards. Colour coding exists exactly for this: so toilet germs never reach the basin.",
                     pl: "Czerwona ściereczka była przy WC i idzie potem do prania. Podział kolorami jest właśnie po to, by zarazki z WC nie trafiły na umywalkę.",
                     hr: "Crvena krpa bila je na WC-u i nakon toga ide u pranje. Odvajanje po bojama postoji upravo zato da klice s WC-a nikad ne dođu na umivaonik.",
                     sr: "Crvena krpa bila je na WC-u i posle toga ide u pranje. Odvajanje po bojama postoji upravo zato da klice sa WC-a nikad ne dođu na lavabo." }
        }
      ]
    },
    {
      id: "hk-bad-s3",
      goal: { de: "Du erkennst am fertigen Bad, was dazugehört und was nicht.",
              en: "You can tell what belongs to a finished bathroom and what does not.",
              pl: "Rozpoznajesz, co należy do gotowej łazienki, a co nie.",
              hr: "Prepoznaješ što spada u gotovu kupaonicu, a što ne.",
              sr: "Prepoznaješ šta spada u gotovo kupatilo, a šta ne." },
      steps: [
        {
          type: "checklist",
          prompt: { de: "Was gehört zu einem fertigen Bad? Wähle alles Richtige.",
                    en: "What belongs to a finished bathroom? Select everything correct.",
                    pl: "Co należy do gotowej łazienki? Zaznacz wszystko poprawne.",
                    hr: "Što spada u gotovu kupaonicu? Odaberi sve točno.",
                    sr: "Šta spada u gotovo kupatilo? Izaberi sve tačno." },
          items: [
            { label: { de: "Spiegel ohne Streifen und ohne Spritzer",
                       en: "Mirror without streaks or splashes", pl: "Lustro bez smug i plam",
                       hr: "Ogledalo bez crta i mrlja", sr: "Ogledalo bez crta i mrlja" }, correct: true },
            { label: { de: "Duschabfluss frei von Haaren", en: "Shower drain free of hair",
                       pl: "Odpływ prysznica bez włosów", hr: "Odvod tuša bez dlaka", sr: "Odvod tuša bez dlaka" }, correct: true },
            { label: { de: "Frische Handtücher, gefaltet und vollzählig",
                       en: "Fresh towels, folded and complete", pl: "Świeże ręczniki, złożone i w komplecie",
                       hr: "Čisti ručnici, složeni i u punom broju", sr: "Čisti peškiri, složeni i u punom broju" }, correct: true },
            { label: { de: "WC mit demselben Tuch wie das Waschbecken geputzt",
                       en: "Toilet cleaned with the same cloth as the basin",
                       pl: "WC umyte tą samą ściereczką co umywalka",
                       hr: "WC očišćen istom krpom kao umivaonik",
                       sr: "WC očišćen istom krpom kao lavabo" }, correct: false },
            { label: { de: "Reiniger sofort nach dem Aufsprühen abgewischt",
                       en: "Cleaner wiped off right after spraying",
                       pl: "Środek starty od razu po spryskaniu",
                       hr: "Sredstvo obrisano odmah nakon prskanja",
                       sr: "Sredstvo obrisano odmah posle prskanja" }, correct: false },
            { label: { de: "Angebrochene Gästeartikel für den nächsten Gast liegen gelassen",
                       en: "Opened guest amenities left for the next guest",
                       pl: "Napoczęte kosmetyki zostawione dla następnego gościa",
                       hr: "Načeti gostinski artikli ostavljeni sljedećem gostu",
                       sr: "Načeti gostinski artikli ostavljeni sledećem gostu" }, correct: false }
          ],
          explain: { de: "Reiniger braucht Einwirkzeit — sofort abgewischt wirkt er nicht, du hast nur gewischt statt desinfiziert. Und angebrochene Seife bekommt kein Gast zweimal.",
                     en: "Cleaner needs contact time — wiped off at once it does nothing, you only wiped instead of disinfecting. And no guest gets opened soap twice.",
                     pl: "Środek potrzebuje czasu działania — starty od razu nic nie robi, tylko przetarłeś zamiast zdezynfekować. A napoczętego mydła nie dostaje drugi gość.",
                     hr: "Sredstvo treba vrijeme djelovanja — obrisano odmah ne radi ništa, samo si prebrisao umjesto dezinficirao. A načeti sapun ne dobiva drugi gost.",
                     sr: "Sredstvo treba vreme delovanja — obrisano odmah ne radi ništa, samo si prebrisao umesto da dezinfikuješ. A načeti sapun ne dobija drugi gost." }
        }
      ]
    }
  ]
};

const bleibezimmer = {
  id: "hk-bleibe",
  title: { de: "Bleibezimmer auffrischen", en: "Refreshing a stayover room",
           pl: "Odświeżanie pokoju na pobycie", hr: "Osvježavanje sobe u kojoj gost ostaje",
           sr: "Osvežavanje sobe u kojoj gost ostaje" },
  goal: { de: "Du frischst ein bewohntes Zimmer auf, ohne die Sachen des Gastes anzurühren.",
          en: "You refresh an occupied room without touching the guest's things.",
          pl: "Odświeżasz zajęty pokój, nie ruszając rzeczy gościa.",
          hr: "Osvježavaš sobu u kojoj gost boravi, ne dirajući njegove stvari.",
          sr: "Osvežavaš sobu u kojoj gost boravi, ne dirajući njegove stvari." },
  minutes: 5,
  stages: [
    {
      id: "hk-bleibe-s1",
      goal: { de: "Du unterscheidest im bewohnten Zimmer, was du anfasst und was dem Gast gehört.",
              en: "In an occupied room you tell apart what you touch and what belongs to the guest.",
              pl: "W zajętym pokoju odróżniasz, czego dotykasz, a co należy do gościa.",
              hr: "U sobi u kojoj gost boravi razlikuješ što diraš, a što pripada gostu.",
              sr: "U sobi u kojoj gost boravi razlikuješ šta diraš, a šta pripada gostu." },
      steps: [
        {
          type: "hotspot",
          scene: "room",
          prompt: { de: "Im Bleibezimmer: Was fasst du an, was nicht? Tippe die Stellen an.",
                    en: "In a stayover room: what do you touch, what not? Tap the spots.",
                    pl: "W pokoju na pobycie: czego dotykasz, a czego nie? Dotknij miejsc.",
                    hr: "U sobi u kojoj gost ostaje: što diraš, a što ne? Dodirni mjesta.",
                    sr: "U sobi u kojoj gost ostaje: šta diraš, a šta ne? Dodirni mesta." },
          hint: { de: "Fünf Stellen. Bei jeder steht, ob sie zu deiner Arbeit gehört — oder zum Gast.",
                  en: "Five spots. Each one says whether it's part of your job — or the guest's.",
                  pl: "Pięć miejsc. Przy każdym jest napisane, czy należy do twojej pracy — czy do gościa.",
                  hr: "Pet mjesta. Kod svakog piše pripada li tvom poslu — ili gostu.",
                  sr: "Pet mesta. Kod svakog piše da li pripada tvom poslu — ili gostu." },
          spots: [
            { id: "bett", x: 58, y: 70, r: 32,
              label: { de: "Bett — glatt ziehen, nicht neu beziehen",
                       en: "Bed — straighten, don't change the linen",
                       pl: "Łóżko — wygładzić, nie zmieniać pościeli",
                       hr: "Krevet — zategni, ne mijenjaj posteljinu",
                       sr: "Krevet — zategni, ne menjaj posteljinu" },
              why: { de: "Bettwäsche wird nur auf Wunsch oder nach Hausregel gewechselt. Glatt gezogen wirkt das Zimmer trotzdem frisch — und spart Wäsche.",
                     en: "Linen is only changed on request or by house rule. Straightened, the room still feels fresh — and saves laundry.",
                     pl: "Pościel zmienia się tylko na życzenie lub według zasad hotelu. Wygładzone łóżko i tak wygląda świeżo — i oszczędza pranie.",
                     hr: "Posteljina se mijenja samo na želju ili po pravilu kuće. Zategnut krevet ipak djeluje svježe — i štedi pranje.",
                     sr: "Posteljina se menja samo na želju ili po pravilu kuće. Zategnut krevet ipak deluje sveže — i štedi pranje." } },
            { id: "schrank", x: 27, y: 48, r: 30,
              label: { de: "Schrank — zu lassen", en: "Wardrobe — leave it closed",
                       pl: "Szafa — nie otwierać", hr: "Ormar — ostavi zatvoren", sr: "Ormar — ostavi zatvoren" },
              why: { de: "Im Bleibezimmer bleibt der Schrank zu. Nur bei Abreise wird er kontrolliert — sonst ist es ein Eingriff in die Privatsphäre.",
                     en: "In a stayover room the wardrobe stays shut. It is only checked on departure — otherwise it's an invasion of privacy.",
                     pl: "W pokoju na pobycie szafa zostaje zamknięta. Sprawdza się ją tylko przy wyjeździe — inaczej to naruszenie prywatności.",
                     hr: "U sobi u kojoj gost ostaje ormar ostaje zatvoren. Provjerava se samo kod odlaska — inače je to zadiranje u privatnost.",
                     sr: "U sobi u kojoj gost ostaje ormar ostaje zatvoren. Proverava se samo kod odlaska — inače je to zadiranje u privatnost." } },
            { id: "lade", x: 87, y: 64, r: 28,
              label: { de: "Nachttisch — nur abstauben, Lade bleibt zu",
                       en: "Nightstand — dust only, drawer stays shut",
                       pl: "Szafka nocna — tylko odkurzyć, szuflada zostaje zamknięta",
                       hr: "Noćni ormarić — samo obriši prašinu, ladica ostaje zatvorena",
                       sr: "Noćni ormarić — samo obriši prašinu, fioka ostaje zatvorena" },
              why: { de: "Um die Sachen des Gastes herum abstauben, nichts wegräumen. Eine geöffnete Lade merkt der Gast — und meldet es an der Rezeption.",
                     en: "Dust around the guest's things, move nothing. A guest notices an opened drawer — and reports it at reception.",
                     pl: "Odkurz wokół rzeczy gościa, niczego nie przekładaj. Gość zauważy otwartą szufladę — i zgłosi to na recepcji.",
                     hr: "Obriši prašinu oko gostovih stvari, ništa ne premještaj. Gost primijeti otvorenu ladicu — i prijavi to na recepciji.",
                     sr: "Obriši prašinu oko gostovih stvari, ništa ne premeštaj. Gost primeti otvorenu fioku — i prijavi to na recepciji." } },
            { id: "korb", x: 35, y: 88, r: 28,
              label: { de: "Papierkorb — leeren, aber nicht durchsuchen",
                       en: "Waste bin — empty it, don't search it",
                       pl: "Kosz — opróżnić, ale nie przeszukiwać",
                       hr: "Koš za smeće — isprazni, ali ne pretražuj",
                       sr: "Korpa za smeće — isprazni, ali ne pretražuj" },
              why: { de: "Leeren gehört immer dazu. Aber im Bleibezimmer gilt: Was neben dem Korb liegt, ist noch Eigentum des Gastes.",
                     en: "Emptying is always part of it. But in a stayover room: whatever lies beside the bin is still the guest's property.",
                     pl: "Opróżnianie należy zawsze do zadań. Ale w pokoju na pobycie: co leży obok kosza, wciąż należy do gościa.",
                     hr: "Pražnjenje uvijek spada u posao. Ali u sobi u kojoj gost ostaje: što leži pored koša još je gostovo vlasništvo.",
                     sr: "Pražnjenje uvek spada u posao. Ali u sobi u kojoj gost ostaje: šta leži pored korpe još je gostovo vlasništvo." } },
            { id: "fenster", x: 74, y: 30, r: 30,
              label: { de: "Fenster — kurz lüften, dann wieder schließen",
                       en: "Window — air briefly, then close again",
                       pl: "Okno — krótko przewietrzyć, potem zamknąć",
                       hr: "Prozor — kratko prozrači, pa zatvori",
                       sr: "Prozor — kratko provetri, pa zatvori" },
              why: { de: "Frische Luft ist die halbe Reinigung. Offen lassen darfst du es nicht: Regen, Insekten und Zugluft kosten das Haus mehr als der Geruch.",
                     en: "Fresh air is half the cleaning. But don't leave it open: rain, insects and draughts cost the house more than the smell.",
                     pl: "Świeże powietrze to połowa sprzątania. Ale nie zostawiaj otwartego: deszcz, owady i przeciąg kosztują hotel więcej niż zapach.",
                     hr: "Svježi zrak je pola čišćenja. Ali ne smiješ ga ostaviti otvoren: kiša, kukci i propuh koštaju kuću više nego miris.",
                     sr: "Svež vazduh je pola čišćenja. Ali ne smeš ga ostaviti otvoren: kiša, insekti i promaja koštaju kuću više nego miris." } }
          ],
          explain: { de: "Das Bleibezimmer ist für die Tage der Reise die Wohnung des Gastes. Du machst es frisch — du räumst es nicht auf.",
                     en: "For the days of the trip, the stayover room is the guest's home. You freshen it up — you don't tidy it away.",
                     pl: "Na czas pobytu pokój jest mieszkaniem gościa. Odświeżasz go — nie porządkujesz go po swojemu.",
                     hr: "Za dane putovanja soba je gostov dom. Ti je osvježiš — ne pospremaš je po svome.",
                     sr: "Za dane putovanja soba je gostov dom. Ti je osvežiš — ne pospremaš je po svome." }
        },
        {
          type: "decide",
          prompt: { de: "Auf dem Schreibtisch liegen Papiere und ein Laptop des Gastes. Du willst abstauben. Was tust du?",
                    en: "The guest's papers and laptop are on the desk. You want to dust. What do you do?",
                    pl: "Na biurku leżą papiery i laptop gościa. Chcesz odkurzyć. Co robisz?",
                    hr: "Na stolu su gostovi papiri i laptop. Želiš obrisati prašinu. Što ćeš učiniti?",
                    sr: "Na stolu su gostovi papiri i laptop. Želiš da obrišeš prašinu. Šta ćeš uraditi?" },
          options: [
            { de: "Alles auf einen Stapel legen und die Fläche wischen",
              en: "Put everything in one pile and wipe the surface",
              pl: "Złożyć wszystko na jeden stos i przetrzeć blat",
              hr: "Složiti sve na hrpu i obrisati površinu",
              sr: "Složiti sve na gomilu i obrisati površinu" },
            { de: "Um die Sachen herum wischen und nichts verschieben",
              en: "Wipe around the things and move nothing",
              pl: "Przetrzeć wokół rzeczy i niczego nie przesuwać",
              hr: "Obrisati oko stvari i ništa ne pomicati",
              sr: "Obrisati oko stvari i ništa ne pomerati" },
            { de: "Sachen ins Regal räumen, damit es ordentlich aussieht",
              en: "Put the things on the shelf so it looks tidy",
              pl: "Schować rzeczy na półkę, żeby było schludnie",
              hr: "Pospremiti stvari na policu da izgleda uredno",
              sr: "Pospremiti stvari na policu da izgleda uredno" },
            { de: "Den Laptop zusammenklappen und darunter wischen",
              en: "Close the laptop and wipe underneath",
              pl: "Zamknąć laptopa i przetrzeć pod spodem",
              hr: "Zaklopiti laptop i obrisati ispod",
              sr: "Zaklopiti laptop i obrisati ispod" }
          ],
          answer: 1,
          explain: { de: "Verschobene Papiere sind für den Gast verlorene Papiere. Staub um den Laptop herum beschwert sich niemand — über ein verschwundenes Dokument sehr wohl.",
                     en: "Moved papers are lost papers to the guest. Nobody complains about dust around a laptop — but they do about a vanished document.",
                     pl: "Przesunięte papiery to dla gościa zgubione papiery. Nikt nie narzeka na kurz wokół laptopa — ale na zaginiony dokument owszem.",
                     hr: "Pomaknuti papiri su za gosta izgubljeni papiri. Nitko se ne žali na prašinu oko laptopa — ali na nestali dokument da.",
                     sr: "Pomereni papiri su za gosta izgubljeni papiri. Niko se ne žali na prašinu oko laptopa — ali na nestali dokument da." }
        }
      ]
    },
    {
      id: "hk-bleibe-s2",
      goal: { de: "Du erkennst, was im Bleibezimmer erledigt wird und was nicht.",
              en: "You can tell what gets done in a stayover room and what does not.",
              pl: "Rozpoznajesz, co robi się w pokoju na pobycie, a czego nie.",
              hr: "Prepoznaješ što se u sobi u kojoj gost ostaje radi, a što ne.",
              sr: "Prepoznaješ šta se u sobi u kojoj gost ostaje radi, a šta ne." },
      steps: [
        {
          type: "checklist",
          prompt: { de: "Was gehört ins Bleibezimmer? Wähle alles Richtige.",
                    en: "What belongs in a stayover room? Select everything correct.",
                    pl: "Co należy do pokoju na pobycie? Zaznacz wszystko poprawne.",
                    hr: "Što spada u sobu u kojoj gost ostaje? Odaberi sve točno.",
                    sr: "Šta spada u sobu u kojoj gost ostaje? Izaberi sve tačno." },
          items: [
            { label: { de: "Müll leeren und Gläser tauschen", en: "Empty the bin and swap the glasses",
                       pl: "Opróżnić kosz i wymienić szklanki", hr: "Isprazniti koš i zamijeniti čaše",
                       sr: "Isprazniti korpu i zameniti čaše" }, correct: true },
            { label: { de: "Bad reinigen und Handtücher tauschen, die am Boden liegen",
                       en: "Clean the bathroom and replace towels lying on the floor",
                       pl: "Posprzątać łazienkę i wymienić ręczniki leżące na podłodze",
                       hr: "Očistiti kupaonicu i zamijeniti ručnike koji leže na podu",
                       sr: "Očistiti kupatilo i zameniti peškire koji leže na podu" }, correct: true },
            { label: { de: "Bett glatt ziehen und Polster aufschütteln",
                       en: "Straighten the bed and plump the pillows",
                       pl: "Wygładzić łóżko i wytrzepać poduszki",
                       hr: "Zategnuti krevet i protresti jastuke",
                       sr: "Zategnuti krevet i protresti jastuke" }, correct: true },
            { label: { de: "Kleidung des Gastes zusammenlegen und in den Schrank hängen",
                       en: "Fold the guest's clothes and hang them in the wardrobe",
                       pl: "Złożyć ubrania gościa i powiesić w szafie",
                       hr: "Složiti gostovu odjeću i objesiti u ormar",
                       sr: "Složiti gostovu odeću i okačiti u ormar" }, correct: false },
            { label: { de: "Bettwäsche jeden Tag wechseln, auch ohne Wunsch",
                       en: "Change the linen every day, even without a request",
                       pl: "Zmieniać pościel codziennie, nawet bez życzenia",
                       hr: "Mijenjati posteljinu svaki dan, i bez želje gosta",
                       sr: "Menjati posteljinu svaki dan, i bez želje gosta" }, correct: false },
            { label: { de: "Angefangene Getränke des Gastes wegwerfen",
                       en: "Throw away the guest's opened drinks",
                       pl: "Wyrzucić napoczęte napoje gościa",
                       hr: "Baciti gostova načeta pića",
                       sr: "Baciti gostova načeta pića" }, correct: false }
          ],
          explain: { de: "Der Unterschied zur Abreise ist einfach: Du reinigst, aber du räumst nicht um. Wäsche nur auf Wunsch — täglicher Wechsel kostet Wasser und ist nicht Hausstandard.",
                     en: "The difference from a departure is simple: you clean, but you don't rearrange. Linen only on request — daily changes cost water and aren't house standard.",
                     pl: "Różnica wobec wyjazdu jest prosta: sprzątasz, ale nie przekładasz. Pościel tylko na życzenie — codzienna zmiana kosztuje wodę i nie jest standardem.",
                     hr: "Razlika u odnosu na odlazak je jednostavna: čistiš, ali ne premještaš. Posteljina samo na želju — svakodnevna zamjena troši vodu i nije standard kuće.",
                     sr: "Razlika u odnosu na odlazak je jednostavna: čistiš, ali ne premeštaš. Posteljina samo na želju — svakodnevna zamena troši vodu i nije standard kuće." }
        }
      ]
    }
  ]
};

const reinigungswagen = {
  id: "hk-wagen",
  title: { de: "Reinigungswagen vorbereiten", en: "Preparing the cleaning trolley",
           pl: "Przygotowanie wózka serwisowego", hr: "Priprema kolica za čišćenje",
           sr: "Priprema kolica za čišćenje" },
  goal: { de: "Du startest die Schicht mit einem Wagen, für den du nicht mehr zurücklaufen musst.",
          en: "You start the shift with a trolley that never sends you back to the store room.",
          pl: "Zaczynasz zmianę z wózkiem, do którego nie musisz wracać po zapasy.",
          hr: "Počinješ smjenu s kolicima zbog kojih se ne moraš vraćati u skladište.",
          sr: "Počinješ smenu sa kolicima zbog kojih ne moraš da se vraćaš u magacin." },
  minutes: 4,
  stages: [
    {
      id: "hk-wagen-s1",
      goal: { de: "Du bestückst den Wagen in der richtigen Reihenfolge mit allem, was die Schicht braucht.",
              en: "You load the trolley in the right order with everything the shift needs.",
              pl: "Ładujesz wózek we właściwej kolejności wszystkim, czego potrzebuje zmiana.",
              hr: "Puniš kolica ispravnim redoslijedom svime što smjena treba.",
              sr: "Puniš kolica ispravnim redosledom svime što smena treba." },
      steps: [
        {
          type: "sequence",
          prompt: { de: "Wie bereitest du den Wagen vor?", en: "How do you prepare the trolley?",
                    pl: "Jak przygotowujesz wózek?", hr: "Kako pripremaš kolica?", sr: "Kako pripremaš kolica?" },
          steps: [
            { de: "Zimmerliste holen und Zimmer zählen", en: "Get the room list and count the rooms",
              pl: "Weź listę pokoi i policz pokoje", hr: "Uzmi popis soba i prebroji sobe",
              sr: "Uzmi spisak soba i prebroj sobe" },
            { de: "Frische Wäsche für alle Zimmer laden", en: "Load fresh linen for all the rooms",
              pl: "Załaduj świeżą pościel na wszystkie pokoje", hr: "Utovari čistu posteljinu za sve sobe",
              sr: "Utovari čistu posteljinu za sve sobe" },
            { de: "Gästeartikel und Papier auffüllen", en: "Restock amenities and paper",
              pl: "Uzupełnij kosmetyki i papier", hr: "Nadopuni gostinske artikle i papir",
              sr: "Nadopuni gostinske artikle i papir" },
            { de: "Chemie und Tücher getrennt einräumen", en: "Load chemicals and cloths separately",
              pl: "Ułóż chemię i ściereczki osobno", hr: "Složi kemiju i krpe odvojeno",
              sr: "Složi hemiju i krpe odvojeno" },
            { de: "Müllsäcke und Wäschesack einhängen", en: "Hang the rubbish and laundry bags",
              pl: "Zawieś worki na śmieci i na pranie", hr: "Objesi vreće za smeće i za rublje",
              sr: "Okači kese za smeće i za veš" },
            { de: "Generalschlüssel am Körper befestigen", en: "Attach the master key to your body",
              pl: "Przypnij klucz uniwersalny do siebie", hr: "Pričvrsti generalni ključ na sebe",
              sr: "Pričvrsti generalni ključ na sebe" }
          ],
          explain: { de: "Zuerst zählen, dann laden: Wer schätzt, läuft mitten in der Schicht dreimal ins Lager zurück. Das kostet mehr Zeit als die ganze Vorbereitung.",
                     en: "Count first, load second: guess it and you'll walk back to the store room three times mid-shift. That costs more time than the whole set-up.",
                     pl: "Najpierw licz, potem ładuj: kto zgaduje, wraca w środku zmiany trzy razy do magazynu. To kosztuje więcej niż całe przygotowanie.",
                     hr: "Prvo broji, pa tovari: tko procjenjuje, usred smjene se tri puta vraća u skladište. To košta više vremena nego cijela priprema.",
                     sr: "Prvo broji, pa tovari: ko procenjuje, usred smene se tri puta vraća u magacin. To košta više vremena nego cela priprema." }
        },
        {
          type: "checklist",
          prompt: { de: "Was gehört auf den Wagen? Wähle alles Richtige.",
                    en: "What belongs on the trolley? Select everything correct.",
                    pl: "Co należy na wózek? Zaznacz wszystko poprawne.",
                    hr: "Što spada na kolica? Odaberi sve točno.",
                    sr: "Šta spada na kolica? Izaberi sve tačno." },
          items: [
            { label: { de: "Wäsche für alle Zimmer der Schicht", en: "Linen for every room of the shift",
                       pl: "Pościel na wszystkie pokoje zmiany", hr: "Posteljina za sve sobe u smjeni",
                       sr: "Posteljina za sve sobe u smeni" }, correct: true },
            { label: { de: "Tücher nach Farben getrennt", en: "Cloths separated by colour",
                       pl: "Ściereczki rozdzielone kolorami", hr: "Krpe odvojene po bojama",
                       sr: "Krpe odvojene po bojama" }, correct: true },
            { label: { de: "Handschuhe und ein zweites Paar zum Wechseln",
                       en: "Gloves and a second pair to change into",
                       pl: "Rękawice i druga para na zmianę",
                       hr: "Rukavice i drugi par za promjenu",
                       sr: "Rukavice i drugi par za promenu" }, correct: true },
            { label: { de: "Der Generalschlüssel, oben in der offenen Ablage",
                       en: "The master key, in the open tray on top",
                       pl: "Klucz uniwersalny, w otwartej tacce na wierzchu",
                       hr: "Generalni ključ, u otvorenoj ladici na vrhu",
                       sr: "Generalni ključ, u otvorenoj fioci na vrhu" }, correct: false },
            { label: { de: "Die private Handtasche und das Telefon",
                       en: "Your private handbag and phone",
                       pl: "Prywatna torebka i telefon",
                       hr: "Privatna torbica i telefon",
                       sr: "Privatna tašna i telefon" }, correct: false },
            { label: { de: "Offene Chemieflaschen neben der frischen Wäsche",
                       en: "Open chemical bottles next to the fresh linen",
                       pl: "Otwarte butelki z chemią obok świeżej pościeli",
                       hr: "Otvorene boce s kemijom pored čiste posteljine",
                       sr: "Otvorene boce sa hemijom pored čiste posteljine" }, correct: false }
          ],
          explain: { de: "Chemie gehört nach unten, Wäsche nach oben: eine umgekippte Flasche verdirbt einen ganzen Stapel. Und der Generalschlüssel liegt nie auf dem Wagen — er bleibt am Körper.",
                     en: "Chemicals belong at the bottom, linen on top: one tipped bottle ruins a whole stack. And the master key never lies on the trolley — it stays on your body.",
                     pl: "Chemia na dół, pościel na górę: jedna przewrócona butelka niszczy cały stos. A klucz uniwersalny nigdy nie leży na wózku — zostaje przy tobie.",
                     hr: "Kemija ide dolje, posteljina gore: jedna prevrnuta boca uništi cijeli stog. A generalni ključ nikad ne leži na kolicima — ostaje na tijelu.",
                     sr: "Hemija ide dole, posteljina gore: jedna prevrnuta boca uništi ceo stog. A generalni ključ nikad ne leži na kolicima — ostaje na telu." }
        }
      ]
    },
    {
      id: "hk-wagen-s2",
      goal: { de: "Du weißt, dass der Wagen nie unbeaufsichtigt im Gang stehen bleibt.",
              en: "You know the trolley is never left unattended in the corridor.",
              pl: "Wiesz, że wózek nigdy nie zostaje bez nadzoru na korytarzu.",
              hr: "Znaš da kolica nikad ne ostaju bez nadzora u hodniku.",
              sr: "Znaš da kolica nikad ne ostaju bez nadzora u hodniku." },
      steps: [
        {
          type: "decide",
          prompt: { de: "Du musst kurz ins Lager. Der Wagen steht im Gang. Was tust du?",
                    en: "You need to pop to the store room. The trolley is in the corridor. What do you do?",
                    pl: "Musisz na chwilę do magazynu. Wózek stoi na korytarzu. Co robisz?",
                    hr: "Moraš nakratko u skladište. Kolica su u hodniku. Što ćeš učiniti?",
                    sr: "Moraš nakratko u magacin. Kolica su u hodniku. Šta ćeš uraditi?" },
          options: [
            { de: "Wagen stehen lassen, es dauert nur zwei Minuten",
              en: "Leave the trolley, it's only two minutes",
              pl: "Zostawić wózek, to tylko dwie minuty",
              hr: "Ostaviti kolica, traje samo dvije minute",
              sr: "Ostaviti kolica, traje samo dva minuta" },
            { de: "Wagen ins offene Zimmer schieben und die Tür anlehnen",
              en: "Push the trolley into the open room and leave the door ajar",
              pl: "Wepchnąć wózek do otwartego pokoju i przymknąć drzwi",
              hr: "Gurnuti kolica u otvorenu sobu i pritvoriti vrata",
              sr: "Gurnuti kolica u otvorenu sobu i pritvoriti vrata" },
            { de: "Wagen mitnehmen oder abschließbar sichern — Schlüssel bleibt bei dir",
              en: "Take the trolley along or lock it — the key stays with you",
              pl: "Zabrać wózek albo go zamknąć — klucz zostaje przy tobie",
              hr: "Povesti kolica sa sobom ili ih zaključati — ključ ostaje kod tebe",
              sr: "Povesti kolica sa sobom ili ih zaključati — ključ ostaje kod tebe" },
            { de: "Einen Gast bitten, kurz aufzupassen", en: "Ask a guest to keep an eye on it",
              pl: "Poprosić gościa, żeby przez chwilę popilnował",
              hr: "Zamoliti gosta da nakratko pripazi", sr: "Zamoliti gosta da nakratko pripazi" }
          ],
          answer: 2,
          explain: { de: "Auf dem Wagen liegen Chemie, Gästeartikel und der Zugang zum halben Haus. Unbeaufsichtigt ist er in zwei Minuten leer — und du musst erklären, wie das passieren konnte.",
                     en: "The trolley holds chemicals, amenities and access to half the hotel. Unattended it is empty in two minutes — and you have to explain how that happened.",
                     pl: "Na wózku jest chemia, kosmetyki i dostęp do pół hotelu. Bez nadzoru będzie pusty w dwie minuty — a ty będziesz tłumaczyć, jak to się stało.",
                     hr: "Na kolicima su kemija, gostinski artikli i pristup pola kuće. Bez nadzora su prazna za dvije minute — a ti moraš objasniti kako se to dogodilo.",
                     sr: "Na kolicima su hemija, gostinski artikli i pristup pola kuće. Bez nadzora su prazna za dva minuta — a ti moraš da objasniš kako se to desilo." }
        }
      ]
    }
  ]
};

const chemie = {
  id: "hk-chemie",
  title: { de: "Sicher mit Reinigungsmitteln", en: "Working safely with cleaning products",
           pl: "Bezpieczna praca ze środkami czystości", hr: "Siguran rad sa sredstvima za čišćenje",
           sr: "Bezbedan rad sa sredstvima za čišćenje" },
  goal: { de: "Du benutzt die Mittel so, dass sie wirken — und niemandem schaden.",
          en: "You use the products so they work — and harm nobody.",
          pl: "Używasz środków tak, by działały — i nikomu nie zaszkodziły.",
          hr: "Koristiš sredstva tako da djeluju — i nikome ne naude.",
          sr: "Koristiš sredstva tako da deluju — i nikome ne naude." },
  minutes: 5,
  stages: [
    {
      id: "hk-chemie-s1",
      goal: { de: "Du benutzt jedes Mittel einzeln und erst, nachdem du das Etikett gelesen hast.",
              en: "You use every product on its own and only after reading the label.",
              pl: "Każdego środka używasz osobno i dopiero po przeczytaniu etykiety.",
              hr: "Svako sredstvo koristiš zasebno i tek nakon što pročitaš etiketu.",
              sr: "Svako sredstvo koristiš zasebno i tek nakon što pročitaš etiketu." },
      steps: [
        {
          type: "decide",
          prompt: { de: "Der Kalk in der Dusche geht nicht weg. Neben dir stehen ein Chlorreiniger und ein saurer Kalklöser. Was tust du?",
                    en: "The limescale in the shower won't come off. Beside you are a chlorine cleaner and an acidic descaler. What do you do?",
                    pl: "Kamień w prysznicu nie schodzi. Obok stoi środek z chlorem i kwasowy odkamieniacz. Co robisz?",
                    hr: "Kamenac u tušu ne popušta. Pored tebe su sredstvo s klorom i kiseli odstranjivač kamenca. Što ćeš učiniti?",
                    sr: "Kamenac u tušu ne popušta. Pored tebe su sredstvo sa hlorom i kiseli odstranjivač kamenca. Šta ćeš uraditi?" },
          options: [
            { de: "Beide zusammen aufsprühen, doppelt hilft doppelt",
              en: "Spray both together, twice as much helps twice as much",
              pl: "Spryskać oboma naraz, podwójnie działa podwójnie",
              hr: "Poprskati oboje zajedno, dvostruko pomaže dvostruko",
              sr: "Poprskati oboje zajedno, duplo pomaže duplo" },
            { de: "Nur den Kalklöser nehmen und ihm Zeit zum Einwirken geben",
              en: "Use only the descaler and give it time to work",
              pl: "Wziąć tylko odkamieniacz i dać mu czas na działanie",
              hr: "Uzeti samo odstranjivač kamenca i dati mu vremena da djeluje",
              sr: "Uzeti samo odstranjivač kamenca i dati mu vremena da deluje" },
            { de: "Erst Chlor, sofort danach die Säure", en: "Chlorine first, the acid right after",
              pl: "Najpierw chlor, zaraz potem kwas", hr: "Prvo klor, odmah zatim kiselina",
              sr: "Prvo hlor, odmah zatim kiselina" },
            { de: "Beides mit heißem Wasser mischen", en: "Mix both with hot water",
              pl: "Zmieszać oba z gorącą wodą", hr: "Pomiješati oboje s vrućom vodom",
              sr: "Pomešati oboje sa vrućom vodom" }
          ],
          answer: 1,
          explain: { de: "Chlor und Säure ergeben zusammen giftiges Chlorgas — es verätzt sofort Augen und Atemwege, und im kleinen Bad ohne Fenster wird die Konzentration schnell lebensgefährlich. Ein Mittel, Einwirkzeit, fertig.",
                     en: "Chlorine and acid together make toxic chlorine gas — it burns your eyes and airways at once, and in a small windowless bathroom the concentration quickly becomes life-threatening. One product, contact time, done.",
                     pl: "Chlor i kwas razem tworzą trujący gaz chlorowy — natychmiast parzy oczy i drogi oddechowe, a w małej łazience bez okna stężenie szybko staje się groźne dla życia. Jeden środek, czas działania, koniec.",
                     hr: "Klor i kiselina zajedno stvaraju otrovni klorni plin — odmah nagriza oči i dišne putove, a u maloj kupaonici bez prozora koncentracija brzo postaje opasna po život. Jedno sredstvo, vrijeme djelovanja, gotovo.",
                     sr: "Hlor i kiselina zajedno stvaraju otrovni hlorni gas — odmah nagriza oči i disajne puteve, a u malom kupatilu bez prozora koncentracija brzo postaje opasna po život. Jedno sredstvo, vreme delovanja, gotovo." }
        },
        {
          type: "sequence",
          prompt: { de: "Wie benutzt du ein neues Reinigungsmittel richtig?",
                    en: "How do you use a new cleaning product correctly?",
                    pl: "Jak prawidłowo używasz nowego środka czystości?",
                    hr: "Kako ispravno koristiš novo sredstvo za čišćenje?",
                    sr: "Kako ispravno koristiš novo sredstvo za čišćenje?" },
          steps: [
            { de: "Etikett lesen — wofür und wie stark verdünnt",
              en: "Read the label — what for and how diluted",
              pl: "Przeczytaj etykietę — do czego i jak rozcieńczyć",
              hr: "Pročitaj etiketu — za što i koliko razrijediti",
              sr: "Pročitaj etiketu — za šta i koliko razblažiti" },
            { de: "Handschuhe anziehen und Fenster oder Tür öffnen",
              en: "Put on gloves and open a window or door",
              pl: "Załóż rękawice i otwórz okno lub drzwi",
              hr: "Obuci rukavice i otvori prozor ili vrata",
              sr: "Obuci rukavice i otvori prozor ili vrata" },
            { de: "Aufsprühen oder auftragen", en: "Spray it on or apply it",
              pl: "Spryskaj lub nałóż", hr: "Poprskaj ili nanesi", sr: "Poprskaj ili nanesi" },
            { de: "Einwirkzeit abwarten", en: "Wait for the contact time",
              pl: "Odczekaj czas działania", hr: "Pričekaj vrijeme djelovanja", sr: "Sačekaj vreme delovanja" },
            { de: "Abwischen und nachspülen", en: "Wipe off and rinse",
              pl: "Zetrzyj i spłucz", hr: "Obriši i isperi", sr: "Obriši i isperi" },
            { de: "Flasche verschließen und zurück auf den Wagen",
              en: "Close the bottle and put it back on the trolley",
              pl: "Zamknij butelkę i odstaw na wózek",
              hr: "Zatvori bocu i vrati je na kolica",
              sr: "Zatvori bocu i vrati je na kolica" }
          ],
          explain: { de: "Das Etikett zuerst zu lesen dauert zwanzig Sekunden. Ein falsch dosiertes Mittel ruiniert eine Duschwand — und die zahlt das Haus, nicht der Gast.",
                     en: "Reading the label first takes twenty seconds. A wrongly dosed product ruins a shower screen — and the house pays for that, not the guest.",
                     pl: "Przeczytanie etykiety zajmuje dwadzieścia sekund. Źle dozowany środek niszczy ściankę prysznica — a płaci za to hotel, nie gość.",
                     hr: "Čitanje etikete traje dvadeset sekundi. Krivo dozirano sredstvo uništi stijenku tuša — a to plaća kuća, ne gost.",
                     sr: "Čitanje etikete traje dvadeset sekundi. Pogrešno dozirano sredstvo uništi pregradu tuša — a to plaća kuća, ne gost." }
        }
      ]
    },
    {
      id: "hk-chemie-s2",
      goal: { de: "Du reagierst richtig, wenn dich ein Mittel trifft, und gehst so mit Chemie um, dass es gar nicht erst passiert.",
              en: "You react correctly when a product hits you, and handle chemicals so it does not happen in the first place.",
              pl: "Reagujesz prawidłowo, gdy środek cię dosięgnie, i obchodzisz się z chemią tak, by do tego w ogóle nie doszło.",
              hr: "Reagiraš ispravno kad te sredstvo pogodi i s kemijom rukuješ tako da do toga uopće ne dođe.",
              sr: "Reaguješ ispravno kad te sredstvo pogodi i hemijom rukuješ tako da do toga uopšte ne dođe." },
      steps: [
        {
          type: "decide",
          prompt: { de: "Beim Sprühen bekommst du Reiniger ins Auge. Was tust du zuerst?",
                    en: "While spraying you get cleaner in your eye. What do you do first?",
                    pl: "Podczas spryskiwania środek dostaje się do oka. Co robisz najpierw?",
                    hr: "Pri prskanju ti sredstvo uđe u oko. Što ćeš prvo učiniti?",
                    sr: "Pri prskanju ti sredstvo uđe u oko. Šta ćeš prvo uraditi?" },
          options: [
            { de: "Auge reiben und weiterarbeiten", en: "Rub the eye and keep working",
              pl: "Przetrzeć oko i pracować dalej", hr: "Protrljati oko i nastaviti raditi",
              sr: "Protrljati oko i nastaviti da radiš" },
            { de: "Sofort mindestens 10 Minuten mit fließendem Wasser spülen und melden",
              en: "Rinse immediately with running water for at least 10 minutes and report it",
              pl: "Natychmiast płukać bieżącą wodą co najmniej 10 minut i zgłosić",
              hr: "Odmah ispirati tekućom vodom najmanje 10 minuta i prijaviti",
              sr: "Odmah ispirati tekućom vodom najmanje 10 minuta i prijaviti" },
            { de: "Kurz abtupfen und schauen, ob es besser wird",
              en: "Dab it briefly and see if it gets better",
              pl: "Krótko przetrzeć i zobaczyć, czy przejdzie",
              hr: "Kratko obrisati i vidjeti hoće li proći",
              sr: "Kratko obrisati i videti da li će proći" },
            { de: "Am Schichtende zum Arzt gehen", en: "Go to the doctor at the end of the shift",
              pl: "Pójść do lekarza po zmianie", hr: "Otići liječniku na kraju smjene",
              sr: "Otići lekaru na kraju smene" }
          ],
          answer: 1,
          explain: { de: "Bei Augenkontakt zählt jede Sekunde: mindestens 10 Minuten spülen verdünnt das Mittel, bevor es die Hornhaut angreift. Reiben drückt es nur tiefer hinein.",
                     en: "With eye contact every second counts: 10 minutes of rinsing dilutes the product before it attacks the cornea. Rubbing only pushes it deeper.",
                     pl: "Przy kontakcie z okiem liczy się każda sekunda: 10 minut płukania rozcieńcza środek, zanim uszkodzi rogówkę. Tarcie wciska go głębiej.",
                     hr: "Kod kontakta s okom svaka sekunda je važna: 10 minuta ispiranja razrijedi sredstvo prije nego nagrize rožnicu. Trljanje ga samo gura dublje.",
                     sr: "Kod kontakta sa okom svaka sekunda je važna: 10 minuta ispiranja razblaži sredstvo pre nego nagrize rožnjaču. Trljanje ga samo gura dublje." }
        },
        {
          type: "checklist",
          prompt: { de: "Sicherer Umgang mit Chemie — was ist richtig?",
                    en: "Handling chemicals safely — what is correct?",
                    pl: "Bezpieczne obchodzenie się z chemią — co jest poprawne?",
                    hr: "Sigurno rukovanje kemijom — što je točno?",
                    sr: "Bezbedno rukovanje hemijom — šta je tačno?" },
          items: [
            { label: { de: "Immer in der Originalflasche mit Etikett lassen",
                       en: "Always keep it in the original bottle with the label",
                       pl: "Zawsze zostawiać w oryginalnej butelce z etykietą",
                       hr: "Uvijek ostaviti u originalnoj boci s etiketom",
                       sr: "Uvek ostaviti u originalnoj boci sa etiketom" }, correct: true },
            { label: { de: "Nur ein Mittel pro Fläche", en: "Only one product per surface",
                       pl: "Tylko jeden środek na powierzchnię", hr: "Samo jedno sredstvo po površini",
                       sr: "Samo jedno sredstvo po površini" }, correct: true },
            { label: { de: "Beim Sprühen lüften und vom Gesicht weg sprühen",
                       en: "Ventilate while spraying and spray away from your face",
                       pl: "Wietrzyć przy spryskiwaniu i kierować z dala od twarzy",
                       hr: "Prozračiti pri prskanju i prskati dalje od lica",
                       sr: "Provetriti pri prskanju i prskati dalje od lica" }, correct: true },
            { label: { de: "Reiniger in eine leere Getränkeflasche umfüllen",
                       en: "Decant cleaner into an empty drinks bottle",
                       pl: "Przelać środek do pustej butelki po napoju",
                       hr: "Preliti sredstvo u praznu bocu od pića",
                       sr: "Presuti sredstvo u praznu flašu od pića" }, correct: false },
            { label: { de: "Zwei Mittel mischen, wenn eines allein nicht reicht",
                       en: "Mix two products if one alone isn't enough",
                       pl: "Zmieszać dwa środki, gdy jeden nie wystarcza",
                       hr: "Pomiješati dva sredstva ako jedno nije dovoljno",
                       sr: "Pomešati dva sredstva ako jedno nije dovoljno" }, correct: false },
            { label: { de: "Sprühflaschen offen im Zimmer stehen lassen",
                       en: "Leave spray bottles open in the room",
                       pl: "Zostawiać otwarte butelki z rozpylaczem w pokoju",
                       hr: "Ostaviti otvorene boce s raspršivačem u sobi",
                       sr: "Ostaviti otvorene boce sa raspršivačem u sobi" }, correct: false }
          ],
          explain: { de: "Eine Getränkeflasche mit Reiniger ist die häufigste Vergiftung im Hotel — ein Kollege oder ein Kind trinkt daraus. Und offene Flaschen im Zimmer erreicht jedes Gästekind.",
                     en: "A drinks bottle filled with cleaner is the most common poisoning in a hotel — a colleague or a child drinks from it. And open bottles in the room are within reach of any guest's child.",
                     pl: "Butelka po napoju ze środkiem to najczęstsze zatrucie w hotelu — kolega albo dziecko się z niej napije. A otwarte butelki w pokoju sięgnie każde dziecko gościa.",
                     hr: "Boca od pića sa sredstvom najčešći je uzrok trovanja u hotelu — kolega ili dijete popije iz nje. A otvorene boce u sobi dohvati svako gostovo dijete.",
                     sr: "Flaša od pića sa sredstvom najčešći je uzrok trovanja u hotelu — kolega ili dete popije iz nje. A otvorene flaše u sobi dohvati svako gostovo dete." }
        }
      ]
    }
  ]
};

export const extraTasks = [badReinigen, bleibezimmer, reinigungswagen, chemie];
