/**
 * Rezeption — Handgriffe, fuenfsprachig.
 *
 * Sprachen: de (Grundsprache), en, pl, hr, sr
 * Kroatisch und Serbisch sind eng verwandt; wo sich die Woerter wirklich
 * unterscheiden, ist das beruecksichtigt (točno/tačno, tko/ko, što/šta,
 * ladica/fioka, tisuća/hiljada). Serbisch in lateinischer Schrift.
 *
 * Kern des Case: Wissen bleibt im Haus. Darum ist die zweite Taetigkeit
 * die Schichtuebergabe — nicht als Formalie, sondern als Handgriff.
 */

const gastEinchecken = {
  id: "rc-checkin",
  title: { de: "Gast einchecken", en: "Checking a guest in", pl: "Zameldowanie gościa",
           hr: "Prijava gosta", sr: "Prijava gosta" },
  goal: { de: "Du checkst einen Gast ein — ruhig, vollständig, ohne Rückfragen hinterher.",
          en: "You check a guest in — calmly, completely, with no questions left over.",
          pl: "Meldujesz gościa — spokojnie, kompletnie, bez pytań na później.",
          hr: "Prijaviš gosta — mirno, potpuno, bez naknadnih pitanja.",
          sr: "Prijaviš gosta — mirno, potpuno, bez naknadnih pitanja." },
  minutes: 5,
  steps: [
    {
      type: "demo",
      scene: "reception",
      title: { de: "Schau dir den Ablauf an", en: "Watch the sequence", pl: "Obejrzyj przebieg",
               hr: "Pogledaj postupak", sr: "Pogledaj postupak" },
      intro: { de: "Sechs Handgriffe. Die Zimmerkarte kommt zuletzt — erst wenn das Zimmer wirklich frei ist.",
               en: "Six moves. The key card comes last — only when the room is really ready.",
               pl: "Sześć kroków. Karta do pokoju na końcu — dopiero gdy pokój jest naprawdę gotowy.",
               hr: "Šest koraka. Kartica sobe dolazi zadnja — tek kad je soba stvarno slobodna.",
               sr: "Šest koraka. Kartica sobe dolazi poslednja — tek kad je soba stvarno slobodna." },
      frames: [
        { caption: { de: "Gast begrüßen", en: "Greet the guest", pl: "Przywitaj gościa",
                     hr: "Pozdravi gosta", sr: "Pozdravi gosta" },
          detail: { de: "Aufstehen, Blickkontakt, Name fragen. Der erste Satz entscheidet, ob der Gast dir später etwas sagt oder sich beschwert.",
                    en: "Stand up, make eye contact, ask for the name. The first sentence decides whether the guest talks to you later or complains.",
                    pl: "Wstań, nawiąż kontakt wzrokowy, zapytaj o nazwisko. Pierwsze zdanie decyduje, czy gość później powie ci coś, czy złoży skargę.",
                    hr: "Ustani, uspostavi kontakt očima, pitaj za prezime. Prva rečenica odlučuje hoće li ti gost kasnije nešto reći ili se žaliti.",
                    sr: "Ustani, uspostavi kontakt očima, pitaj za prezime. Prva rečenica odlučuje da li će ti gost kasnije nešto reći ili će se žaliti." } },
        { caption: { de: "Buchung suchen", en: "Find the booking", pl: "Znajdź rezerwację",
                     hr: "Pronađi rezervaciju", sr: "Pronađi rezervaciju" },
          detail: { de: "Nach Nachname und Anreisedatum suchen. Findest du nichts, frag nach der Buchungsnummer — nicht raten.",
                    en: "Search by surname and arrival date. If you find nothing, ask for the booking number — don't guess.",
                    pl: "Szukaj po nazwisku i dacie przyjazdu. Jeśli nic nie znajdziesz, poproś o numer rezerwacji — nie zgaduj.",
                    hr: "Traži po prezimenu i datumu dolaska. Ako ništa ne nađeš, pitaj za broj rezervacije — nemoj nagađati.",
                    sr: "Traži po prezimenu i datumu dolaska. Ako ništa ne nađeš, pitaj za broj rezervacije — nemoj da nagađaš." } },
        { caption: { de: "Daten prüfen", en: "Check the details", pl: "Sprawdź dane",
                     hr: "Provjeri podatke", sr: "Proveri podatke" },
          detail: { de: "Nächte, Personen, Verpflegung und Zahlungsart laut vorlesen. So fällt ein Fehler jetzt auf und nicht bei der Abreise.",
                    en: "Read out nights, guests, board and payment method. A mistake shows up now, not at check-out.",
                    pl: "Przeczytaj na głos noce, liczbę osób, wyżywienie i sposób płatności. Błąd wyjdzie teraz, a nie przy wyjeździe.",
                    hr: "Naglas pročitaj noćenja, broj osoba, pansion i način plaćanja. Tako se greška vidi sada, a ne kod odlaska.",
                    sr: "Naglas pročitaj noćenja, broj osoba, pansion i način plaćanja. Tako se greška vidi sada, a ne kod odlaska." } },
        { caption: { de: "Meldezettel ausfüllen", en: "Fill in the registration form", pl: "Wypełnij kartę meldunkową",
                     hr: "Ispuni prijavni list", sr: "Popuni prijavni list" },
          detail: { de: "Ausweis zeigen lassen, Meldezettel ausfüllen, unterschreiben lassen. Das ist Pflicht und wird geprüft.",
                    en: "Ask for the ID, fill in the registration form, have it signed. It's required by law and it does get checked.",
                    pl: "Poproś o dokument, wypełnij kartę meldunkową, daj do podpisu. To obowiązek i bywa kontrolowany.",
                    hr: "Zatraži osobnu, ispuni prijavni list, daj na potpis. To je obveza i provjerava se.",
                    sr: "Zatraži ličnu kartu, popuni prijavni list, daj na potpis. To je obaveza i proverava se." } },
        { caption: { de: "Zimmerkarte ausgeben", en: "Hand over the key card", pl: "Wydaj kartę do pokoju",
                     hr: "Izdaj karticu sobe", sr: "Izdaj karticu sobe" },
          detail: { de: "Nur ein Zimmer ausgeben, das Housekeeping freigegeben hat. Steht es noch auf „in Arbeit\", wartet der Gast lieber unten als vor einer schmutzigen Tür.",
                    en: "Only hand out a room housekeeping has released. If it still says \"in progress\", the guest waits downstairs rather than at a dirty door.",
                    pl: "Wydawaj tylko pokój zwolniony przez housekeeping. Jeśli jest jeszcze „w trakcie\", gość lepiej poczeka na dole niż pod brudnymi drzwiami.",
                    hr: "Izdaj samo sobu koju je housekeeping oslobodio. Ako još stoji „u radu\", gost radije čeka dolje nego pred prljavim vratima.",
                    sr: "Izdaj samo sobu koju je housekeeping oslobodio. Ako još stoji „u radu\", gost radije čeka dole nego pred prljavim vratima." } },
        { caption: { de: "Fertig", en: "Done", pl: "Gotowe", hr: "Gotovo", sr: "Gotovo" },
          detail: { de: "Weg zum Zimmer, Frühstückszeit und WLAN sagen — und alles Besondere ins Übergabebuch schreiben.",
                    en: "Explain the way to the room, breakfast time and wi-fi — and write anything special into the handover book.",
                    pl: "Powiedz drogę do pokoju, godziny śniadania i wi-fi — a wszystko szczególne zapisz w książce przekazania.",
                    hr: "Reci put do sobe, vrijeme doručka i wi-fi — a sve posebno upiši u knjigu primopredaje.",
                    sr: "Reci put do sobe, vreme doručka i wi-fi — a sve posebno upiši u knjigu primopredaje." } }
      ]
    },
    {
      type: "sequence",
      prompt: { de: "Jetzt du — in welcher Reihenfolge?", en: "Now you — in what order?",
                pl: "Teraz ty — w jakiej kolejności?", hr: "Sada ti — kojim redoslijedom?",
                sr: "Sada ti — kojim redosledom?" },
      steps: [
        { de: "Gast begrüßen", en: "Greet the guest", pl: "Przywitaj gościa",
          hr: "Pozdravi gosta", sr: "Pozdravi gosta" },
        { de: "Buchung suchen", en: "Find the booking", pl: "Znajdź rezerwację",
          hr: "Pronađi rezervaciju", sr: "Pronađi rezervaciju" },
        { de: "Daten prüfen", en: "Check the details", pl: "Sprawdź dane",
          hr: "Provjeri podatke", sr: "Proveri podatke" },
        { de: "Meldezettel ausfüllen", en: "Fill in the registration form", pl: "Wypełnij kartę meldunkową",
          hr: "Ispuni prijavni list", sr: "Popuni prijavni list" },
        { de: "Zimmerkarte ausgeben", en: "Hand over the key card", pl: "Wydaj kartę do pokoju",
          hr: "Izdaj karticu sobe", sr: "Izdaj karticu sobe" },
        { de: "Weg, Frühstück und WLAN erklären", en: "Explain the way, breakfast and wi-fi",
          pl: "Wyjaśnij drogę, śniadanie i wi-fi", hr: "Objasni put, doručak i wi-fi",
          sr: "Objasni put, doručak i wi-fi" }
      ],
      explain: { de: "Erst prüfen, dann Karte: Wer die Karte vorher gibt, holt den Gast bei einem Fehler aus dem Zimmer zurück.",
                 en: "Check first, card after: hand over the card too early and you have to fetch the guest back out of the room.",
                 pl: "Najpierw sprawdzenie, potem karta: kto da kartę wcześniej, przy błędzie musi ściągać gościa z pokoju.",
                 hr: "Prvo provjera, pa kartica: tko da karticu prije, kod greške mora gosta vraćati iz sobe.",
                 sr: "Prvo provera, pa kartica: ko da karticu pre toga, kod greške mora gosta da vraća iz sobe." }
    },
    {
      type: "decide",
      prompt: { de: "Der Gast steht da, aber das Zimmer ist im System noch nicht freigegeben. Was tust du?",
                en: "The guest is standing there, but the room isn't released in the system yet. What do you do?",
                pl: "Gość stoi przy ladzie, ale pokój nie jest jeszcze zwolniony w systemie. Co robisz?",
                hr: "Gost stoji pred tobom, ali soba u sustavu još nije oslobođena. Što ćeš učiniti?",
                sr: "Gost stoji pred tobom, ali soba u sistemu još nije oslobođena. Šta ćeš uraditi?" },
      options: [
        { de: "Karte trotzdem geben, wird schon sauber sein", en: "Give the card anyway, it's probably clean",
          pl: "Daj kartę mimo to, pewnie jest czysto", hr: "Ipak daj karticu, vjerojatno je čisto",
          sr: "Ipak daj karticu, verovatno je čisto" },
        { de: "Ein anderes Zimmer geben, ohne es jemandem zu sagen",
          en: "Give a different room without telling anyone",
          pl: "Daj inny pokój i nikomu nie mów",
          hr: "Daj drugu sobu i nikome ne reci",
          sr: "Daj drugu sobu i nikome ne reci" },
        { de: "Beim Housekeeping nachfragen, dem Gast die Wartezeit sagen und Gepäck annehmen",
          en: "Ask housekeeping, tell the guest how long it will take and take the luggage",
          pl: "Zapytaj housekeeping, podaj gościowi czas oczekiwania i przyjmij bagaż",
          hr: "Pitaj housekeeping, reci gostu koliko će trajati i primi prtljagu",
          sr: "Pitaj housekeeping, reci gostu koliko će trajati i primi prtljag" },
        { de: "Den Gast wegschicken und später wiederkommen lassen",
          en: "Send the guest away and have them come back later",
          pl: "Odeślij gościa i każ wrócić później",
          hr: "Pošalji gosta i neka se vrati kasnije",
          sr: "Pošalji gosta i neka se vrati kasnije" }
      ],
      answer: 2,
      explain: { de: "Eine ehrliche Wartezeit von zwanzig Minuten akzeptiert fast jeder Gast. Ein schmutziges Zimmer verzeiht fast keiner.",
                 en: "Almost every guest accepts an honest twenty-minute wait. Almost nobody forgives a dirty room.",
                 pl: "Uczciwe dwadzieścia minut czekania zaakceptuje prawie każdy gość. Brudnego pokoju nie wybaczy prawie nikt.",
                 hr: "Poštenih dvadeset minuta čekanja prihvatit će gotovo svaki gost. Prljavu sobu gotovo nitko ne oprašta.",
                 sr: "Poštenih dvadeset minuta čekanja prihvatiće skoro svaki gost. Prljavu sobu skoro niko ne oprašta." }
    },
    {
      type: "checklist",
      prompt: { de: "Was muss beim Check-in wirklich erledigt sein? Wähle alles Richtige.",
                en: "What really has to be done at check-in? Select everything correct.",
                pl: "Co naprawdę musi być zrobione przy zameldowaniu? Zaznacz wszystko poprawne.",
                hr: "Što stvarno mora biti obavljeno kod prijave? Odaberi sve točno.",
                sr: "Šta stvarno mora da bude obavljeno kod prijave? Izaberi sve tačno." },
      items: [
        { label: { de: "Meldezettel ausgefüllt und unterschrieben", en: "Registration form filled in and signed",
                   pl: "Karta meldunkowa wypełniona i podpisana", hr: "Prijavni list ispunjen i potpisan",
                   sr: "Prijavni list popunjen i potpisan" }, correct: true },
        { label: { de: "Zimmer vom Housekeeping freigegeben", en: "Room released by housekeeping",
                   pl: "Pokój zwolniony przez housekeeping", hr: "Soba oslobođena od housekeepinga",
                   sr: "Soba oslobođena od housekeepinga" }, correct: true },
        { label: { de: "Nächte, Personen und Zahlungsart bestätigt", en: "Nights, guests and payment method confirmed",
                   pl: "Potwierdzone noce, liczba osób i sposób płatności", hr: "Potvrđena noćenja, broj osoba i način plaćanja",
                   sr: "Potvrđena noćenja, broj osoba i način plaćanja" }, correct: true },
        { label: { de: "Kopie des Ausweises im Papierstapel unter dem Tresen", en: "Copy of the ID in the paper pile under the counter",
                   pl: "Kopia dokumentu w stosie papierów pod ladą", hr: "Kopija osobne u hrpi papira ispod pulta",
                   sr: "Kopija lične karte u gomili papira ispod pulta" }, correct: false },
        { label: { de: "Kreditkartennummer auf einen Zettel notiert", en: "Credit card number written on a note",
                   pl: "Numer karty kredytowej zapisany na kartce", hr: "Broj kreditne kartice zapisan na papiriću",
                   sr: "Broj kreditne kartice zapisan na papiriću" }, correct: false }
      ],
      explain: { de: "Gästedaten gehören ins System, nicht auf lose Zettel. Ein Zettel unter dem Tresen ist ein Datenschutzproblem mit Beinen.",
                 en: "Guest data belongs in the system, not on loose notes. A note under the counter is a data protection problem with legs.",
                 pl: "Dane gości należą do systemu, nie na luźne kartki. Kartka pod ladą to problem z ochroną danych, który chodzi.",
                 hr: "Podaci gostiju idu u sustav, ne na papiriće. Papirić ispod pulta je problem zaštite podataka koji hoda.",
                 sr: "Podaci gostiju idu u sistem, ne na papiriće. Papirić ispod pulta je problem zaštite podataka koji hoda." }
    }
  ]
};

const schichtuebergabe = {
  id: "rc-uebergabe",
  title: { de: "Schichtübergabe & Wissen sichern", en: "Shift handover & securing knowledge",
           pl: "Przekazanie zmiany i zabezpieczenie wiedzy", hr: "Primopredaja smjene i osiguranje znanja",
           sr: "Primopredaja smene i osiguranje znanja" },
  goal: { de: "Du gibst dein Wissen so weiter, dass es im Haus bleibt — auch wenn du gehst.",
          en: "You pass on your knowledge so that it stays in the house — even after you leave.",
          pl: "Przekazujesz swoją wiedzę tak, by została w hotelu — także gdy odejdziesz.",
          hr: "Predaješ svoje znanje tako da ostane u kući — i kad ti odeš.",
          sr: "Predaješ svoje znanje tako da ostane u kući — i kad ti odeš." },
  minutes: 6,
  steps: [
    {
      type: "sequence",
      prompt: { de: "In welcher Reihenfolge übergibst du eine Schicht?",
                en: "In what order do you hand over a shift?",
                pl: "W jakiej kolejności przekazujesz zmianę?",
                hr: "Kojim redoslijedom predaješ smjenu?",
                sr: "Kojim redosledom predaješ smenu?" },
      steps: [
        { de: "Übergabebuch während der Schicht mitschreiben", en: "Write in the handover book during the shift",
          pl: "Zapisuj w książce przekazania w trakcie zmiany", hr: "Piši u knjigu primopredaje tijekom smjene",
          sr: "Piši u knjigu primopredaje tokom smene" },
        { de: "Offene Punkte am Ende durchgehen", en: "Go through the open items at the end",
          pl: "Na koniec przejrzyj otwarte punkty", hr: "Na kraju prođi otvorene točke",
          sr: "Na kraju prođi otvorene tačke" },
        { de: "Kolleg:in die Punkte laut vorlesen", en: "Read the items out loud to your colleague",
          pl: "Przeczytaj punkty na głos koleżance lub koledze", hr: "Kolegi pročitaj točke naglas",
          sr: "Kolegi pročitaj tačke naglas" },
        { de: "Rückfragen klären und ergänzen", en: "Answer questions and add what's missing",
          pl: "Wyjaśnij pytania i uzupełnij", hr: "Razjasni pitanja i dopuni",
          sr: "Razjasni pitanja i dopuni" },
        { de: "Kassa und Schlüssel gemeinsam zählen", en: "Count cash and keys together",
          pl: "Policzcie razem kasę i klucze", hr: "Zajedno prebrojite blagajnu i ključeve",
          sr: "Zajedno prebrojte kasu i ključeve" },
        { de: "Beide zeichnen die Übergabe ab", en: "Both sign off the handover",
          pl: "Oboje podpisujecie przekazanie", hr: "Oboje potpišete primopredaju",
          sr: "Oboje potpišete primopredaju" }
      ],
      explain: { de: "Mitschreiben während der Schicht ist der entscheidende Schritt: Am Ende erinnert sich niemand mehr an den Anruf von vor sechs Stunden.",
                 en: "Writing during the shift is the decisive step: at the end nobody remembers the phone call from six hours ago.",
                 pl: "Zapisywanie w trakcie zmiany to kluczowy krok: pod koniec nikt nie pamięta telefonu sprzed sześciu godzin.",
                 hr: "Pisanje tijekom smjene je ključan korak: na kraju se nitko ne sjeća poziva od prije šest sati.",
                 sr: "Pisanje tokom smene je ključan korak: na kraju se niko ne seća poziva od pre šest sati." }
    },
    {
      type: "decide",
      prompt: { de: "Eine erfahrene Kollegin zeigt dir einen Trick im alten Buchungssystem. Was tust du?",
                en: "An experienced colleague shows you a trick in the old booking system. What do you do?",
                pl: "Doświadczona koleżanka pokazuje ci trik w starym systemie rezerwacji. Co robisz?",
                hr: "Iskusna kolegica ti pokaže trik u starom sustavu rezervacija. Što ćeš učiniti?",
                sr: "Iskusna koleginica ti pokaže trik u starom sistemu rezervacija. Šta ćeš uraditi?" },
      options: [
        { de: "Gut merken, du wirst es schon behalten", en: "Memorise it, you'll remember",
          pl: "Zapamiętaj, na pewno się utrzyma w głowie", hr: "Dobro zapamti, valjda ćeš zadržati",
          sr: "Dobro zapamti, valjda ćeš zadržati" },
        { de: "„Zeig es mir nochmal langsam — ich schreibe es auf.\"",
          en: "\"Show me again slowly — I'll write it down.\"",
          pl: "„Pokaż mi jeszcze raz powoli — zapiszę to.\"",
          hr: "„Pokaži mi još jednom polako — zapisat ću.\"",
          sr: "„Pokaži mi još jednom polako — zapisaću.\"" },
        { de: "Sie bitten, es später selbst zu dokumentieren", en: "Ask her to document it herself later",
          pl: "Poproś, żeby sama to później opisała", hr: "Zamoli je da to poslije sama dokumentira",
          sr: "Zamoli je da to kasnije sama dokumentuje" },
        { de: "Nichts tun, du fragst einfach wieder, wenn es soweit ist",
          en: "Do nothing, you'll just ask again when the time comes",
          pl: "Nic nie rób, zapytasz znowu, gdy będzie trzeba",
          hr: "Ne radi ništa, pitat ćeš opet kad zatreba",
          sr: "Ne radi ništa, pitaćeš opet kad zatreba" }
      ],
      answer: 1,
      explain: { de: "Der Satz „zeig es mir und ich schreibe es auf\" kostet die Erfahrene zwei Minuten und spart dem Haus die nächste Einarbeitung.",
                 en: "The sentence \"show me and I'll write it down\" costs her two minutes and saves the house the next round of training.",
                 pl: "Zdanie „pokaż mi, a ja to zapiszę\" kosztuje ją dwie minuty, a hotelowi oszczędza kolejne wdrażanie.",
                 hr: "Rečenica „pokaži mi i ja ću zapisati\" košta iskusnu kolegicu dvije minute, a kući štedi sljedeće uvođenje.",
                 sr: "Rečenica „pokaži mi i ja ću zapisati\" košta iskusnu koleginicu dva minuta, a kući štedi sledeće uvođenje." }
    },
    {
      type: "checklist",
      prompt: { de: "Was gehört ins Übergabebuch? Wähle alles Richtige.",
                en: "What belongs in the handover book? Select everything correct.",
                pl: "Co należy do książki przekazania? Zaznacz wszystko poprawne.",
                hr: "Što spada u knjigu primopredaje? Odaberi sve točno.",
                sr: "Šta spada u knjigu primopredaje? Izaberi sve tačno." },
      items: [
        { label: { de: "Offene Punkte mit Name und Zimmernummer", en: "Open items with name and room number",
                   pl: "Otwarte punkty z nazwiskiem i numerem pokoju", hr: "Otvorene točke s imenom i brojem sobe",
                   sr: "Otvorene tačke sa imenom i brojem sobe" }, correct: true },
        { label: { de: "Sonderfälle: was war anders als sonst und wie hast du es gelöst",
                   en: "Special cases: what was different and how you solved it",
                   pl: "Przypadki szczególne: co było inaczej i jak to rozwiązałeś",
                   hr: "Posebni slučajevi: što je bilo drukčije i kako si riješio",
                   sr: "Posebni slučajevi: šta je bilo drugačije i kako si rešio" }, correct: true },
        { label: { de: "Zusagen an Gäste, die noch jemand einlösen muss",
                   en: "Promises made to guests that someone still has to keep",
                   pl: "Obietnice dane gościom, które ktoś musi jeszcze spełnić",
                   hr: "Obećanja gostima koja netko još mora ispuniti",
                   sr: "Obećanja gostima koja neko još mora da ispuni" }, correct: true },
        { label: { de: "Passwörter für das Buchungssystem", en: "Passwords for the booking system",
                   pl: "Hasła do systemu rezerwacji", hr: "Lozinke za sustav rezervacija",
                   sr: "Lozinke za sistem rezervacija" }, correct: false },
        { label: { de: "Persönliche Meinungen über Gäste oder Kolleg:innen",
                   en: "Personal opinions about guests or colleagues",
                   pl: "Osobiste opinie o gościach lub współpracownikach",
                   hr: "Osobna mišljenja o gostima ili kolegama",
                   sr: "Lična mišljenja o gostima ili kolegama" }, correct: false }
      ],
      explain: { de: "Ins Buch kommt, was die nächste Schicht braucht. Passwörter gehören in den Passwortspeicher des Hauses, nicht in ein Buch am Tresen.",
                 en: "The book holds what the next shift needs. Passwords belong in the house's password store, not in a book on the counter.",
                 pl: "W książce jest to, czego potrzebuje następna zmiana. Hasła należą do firmowego menedżera haseł, nie do zeszytu na ladzie.",
                 hr: "U knjigu ide ono što treba sljedećoj smjeni. Lozinke idu u kućni spremnik lozinki, a ne u knjigu na pultu.",
                 sr: "U knjigu ide ono što treba sledećoj smeni. Lozinke idu u kućni čuvar lozinki, a ne u knjigu na pultu." }
    },
    {
      type: "decide",
      prompt: { de: "Unter der Tastatur klebt ein Zettel mit dem Passwort fürs Buchungssystem. Was tust du?",
                en: "There's a note with the booking system password stuck under the keyboard. What do you do?",
                pl: "Pod klawiaturą przyklejona jest kartka z hasłem do systemu rezerwacji. Co robisz?",
                hr: "Ispod tipkovnice je zalijepljen papirić s lozinkom za sustav rezervacija. Što ćeš učiniti?",
                sr: "Ispod tastature je zalepljen papirić sa lozinkom za sistem rezervacija. Šta ćeš uraditi?" },
      options: [
        { de: "Nichts, alle machen das so", en: "Nothing, everyone does it that way",
          pl: "Nic, wszyscy tak robią", hr: "Ništa, svi tako rade", sr: "Ništa, svi tako rade" },
        { de: "Den Zettel abfotografieren und aufs Handy legen",
          en: "Photograph the note and keep it on your phone",
          pl: "Zrób zdjęcie kartki i trzymaj w telefonie",
          hr: "Fotografiraj papirić i drži ga na mobitelu",
          sr: "Fotografiši papirić i drži ga na telefonu" },
        { de: "Den Zettel in die Lade legen, da sieht ihn kein Gast",
          en: "Put the note in the drawer, no guest sees it there",
          pl: "Włóż kartkę do szuflady, tam gość jej nie zobaczy",
          hr: "Stavi papirić u ladicu, ondje ga gost ne vidi",
          sr: "Stavi papirić u fioku, tamo ga gost ne vidi" },
        { de: "Chef:in ansprechen, eigenen Zugang bekommen, Zettel vernichten",
          en: "Talk to your manager, get your own login, destroy the note",
          pl: "Porozmawiaj z szefem, załóż własny dostęp, zniszcz kartkę",
          hr: "Javi se šefu, dobij vlastiti pristup, uništi papirić",
          sr: "Javi se šefu, dobij sopstveni pristup, uništi papirić" }
      ],
      answer: 3,
      explain: { de: "Ein eigener Zugang je Person zeigt, wer was gebucht oder storniert hat. Ein Zettel unter der Tastatur zeigt gar nichts — und liegt am offenen Tresen.",
                 en: "One login per person shows who booked or cancelled what. A note under the keyboard shows nothing — and it sits at an open counter.",
                 pl: "Własny dostęp dla każdej osoby pokazuje, kto co zarezerwował lub anulował. Kartka pod klawiaturą nie pokazuje nic — a leży przy otwartej ladzie.",
                 hr: "Vlastiti pristup po osobi pokazuje tko je što rezervirao ili otkazao. Papirić ispod tipkovnice ne pokazuje ništa — a leži na otvorenom pultu.",
                 sr: "Sopstveni pristup po osobi pokazuje ko je šta rezervisao ili otkazao. Papirić ispod tastature ne pokazuje ništa — a leži na otvorenom pultu." }
    }
  ]
};

export const receptionTasks = {
  id: "reception",
  name: { de: "Rezeption", en: "Reception", pl: "Recepcja", hr: "Recepcija", sr: "Recepcija" },
  tagline: { de: "Gäste empfangen, Wissen weitergeben", en: "Welcome guests, pass on knowledge",
             pl: "Przyjmuj gości, przekazuj wiedzę", hr: "Dočekaj goste, prenesi znanje",
             sr: "Dočekaj goste, prenesi znanje" },
  accent: "#7c3aed",
  icon: "ConciergeBell",
  blurb: { de: "Der Tresen ist das Gedächtnis des Hauses. Hier lernst du, wie es gefüllt wird.",
           en: "The front desk is the memory of the house. Here you learn how it gets filled.",
           pl: "Recepcja to pamięć hotelu. Tu uczysz się, jak ją zapełniać.",
           hr: "Recepcija je pamćenje kuće. Ovdje učiš kako se ono puni.",
           sr: "Recepcija je pamćenje kuće. Ovde učiš kako se ono puni." },
  tasks: [gastEinchecken, schichtuebergabe]
};
