/**
 * Oberflaechentexte der Sprachhilfe
 * =================================
 * Die Begriffe selbst sind Deutsch — das ist der Lernstoff. Die BEDIENUNG
 * muss trotzdem ohne ein Wort Deutsch verstaendlich sein, sonst kommt niemand
 * bis zur ersten Aufgabe. Deshalb liegt hier jeder Knopf siebensprachig vor.
 *
 * Die Sprachen sind genau die, die der Wortschatz mitbringt
 * (src/data/hotelVokabeln.json): de + en, pl, hr, sr, tr, sl.
 *
 * ACHTUNG Slowakisch: Der Wortschatz hat SL = Slowenisch, nicht SK =
 * Slowakisch. Die 46 Begriffe des Kurses haben dagegen sk. Wer Slowakisch
 * braucht, muss es im Wortschatz ergaenzen — hier reicht dann eine Zeile.
 */

export const LANGS = [
  ["de", "Deutsch",      "DE"],
  ["en", "English",      "EN"],
  ["pl", "Polski",       "PL"],
  ["hr", "Hrvatski",     "HR"],
  ["sr", "Srpski",       "SR"],
  ["tr", "Türkçe",       "TR"],
  ["sl", "Slovenščina",  "SL"]
];

export const LANG_CODES = LANGS.map(([code]) => code);

/** Holt den Text in der gewuenschten Sprache, Deutsch als Rueckfall. */
export function t(field, lang) {
  if (field === null || field === undefined) return "";
  if (typeof field === "string") return field;
  return field[lang] || field.de || "";
}

export const UI = {
  /* ------------------------------------------------------ Rollenauswahl */
  pickRole: { de: "Für welche Arbeit brauchst du die Wörter?",
              en: "Which job do you need the words for?",
              pl: "Do jakiej pracy potrzebujesz tych słów?",
              hr: "Za koji posao trebaš ove riječi?",
              sr: "Za koji posao ti trebaju ove reči?",
              tr: "Kelimelere hangi iş için ihtiyacın var?",
              sl: "Za katero delo potrebuješ te besede?" },
  pickHint: { de: "Wähle deinen Bereich. Du lernst nur die Begriffe, die dort wirklich fallen.",
              en: "Choose your area. You only learn the terms that actually come up there.",
              pl: "Wybierz swój obszar. Uczysz się tylko słów, które naprawdę tam padają.",
              hr: "Odaberi svoje područje. Učiš samo pojmove koji se tamo stvarno koriste.",
              sr: "Izaberi svoje područje. Učiš samo pojmove koji se tamo stvarno koriste.",
              tr: "Alanını seç. Sadece orada gerçekten geçen kelimeleri öğrenirsin.",
              sl: "Izberi svoje področje. Učiš se samo izrazov, ki se tam res uporabljajo." },
  yourLang: { de: "Deine Sprache", en: "Your language", pl: "Twój język", hr: "Tvoj jezik",
              sr: "Tvoj jezik", tr: "Senin dilin", sl: "Tvoj jezik" },
  langHint: { de: "Deutsche Begriffe bekommen eine Übersetzung in dieser Sprache.",
              en: "German terms get a translation into this language.",
              pl: "Niemieckie słowa dostają tłumaczenie na ten język.",
              hr: "Njemački pojmovi dobivaju prijevod na ovaj jezik.",
              sr: "Nemački pojmovi dobijaju prevod na ovaj jezik.",
              tr: "Almanca kelimeler bu dile çevrilir.",
              sl: "Nemški izrazi dobijo prevod v ta jezik." },
  words:     { de: "Wörter", en: "words", pl: "słowa", hr: "riječi", sr: "reči",
               tr: "kelime", sl: "besede" },
  exercises: { de: "Aufgaben", en: "exercises", pl: "zadania", hr: "zadaci", sr: "zadaci",
               tr: "alıştırma", sl: "naloge" },
  switchRole:{ de: "Bereich wechseln", en: "Switch area", pl: "Zmień obszar",
               hr: "Promijeni područje", sr: "Promeni područje",
               tr: "Alanı değiştir", sl: "Zamenjaj področje" },
  days:      { de: "Tage", en: "days", pl: "dni", hr: "dana", sr: "dana", tr: "gün", sl: "dni" },

  /* ---------------------------------------------------------- Umschalter */
  tabLearn:  { de: "Lernen", en: "Learn", pl: "Nauka", hr: "Učenje", sr: "Učenje",
               tr: "Öğren", sl: "Učenje" },
  tabTrain:  { de: "Trainieren", en: "Practice", pl: "Trening", hr: "Vježbanje",
               sr: "Vežbanje", tr: "Alıştırma", sl: "Vadba" },
  tabCourse: { de: "Kurs", en: "Course", pl: "Kurs", hr: "Tečaj", sr: "Kurs",
               tr: "Kurs", sl: "Tečaj" },

  /* -------------------------------------------------------- Lernen-Teil */
  learnHead: { de: "Deine Wörter", en: "Your words", pl: "Twoje słowa", hr: "Tvoje riječi",
               sr: "Tvoje reči", tr: "Kelimelerin", sl: "Tvoje besede" },
  learnHint: { de: "Erst lesen und anhören, dann trainieren. Der Balken zeigt, wie gut ein Wort sitzt.",
               en: "First read and listen, then practise. The bar shows how well a word sticks.",
               pl: "Najpierw czytaj i słuchaj, potem ćwicz. Pasek pokazuje, jak dobrze siedzi słowo.",
               hr: "Prvo čitaj i slušaj, onda vježbaj. Traka pokazuje koliko dobro riječ sjedi.",
               sr: "Prvo čitaj i slušaj, pa onda vežbaj. Traka pokazuje koliko dobro reč sedi.",
               tr: "Önce oku ve dinle, sonra çalış. Çubuk kelimenin ne kadar oturduğunu gösterir.",
               sl: "Najprej beri in poslušaj, nato vadi. Črta pokaže, kako dobro beseda sedi." },
  block:     { de: "Block", en: "Block", pl: "Blok", hr: "Blok", sr: "Blok", tr: "Blok", sl: "Blok" },
  trainBlock:{ de: "Block trainieren", en: "Practise block", pl: "Ćwicz blok",
               hr: "Vježbaj blok", sr: "Vežbaj blok", tr: "Bloğu çalış", sl: "Vadi blok" },
  listen:    { de: "Anhören", en: "Listen", pl: "Posłuchaj", hr: "Poslušaj", sr: "Slušaj",
               tr: "Dinle", sl: "Poslušaj" },
  learned:   { de: "gelernt", en: "learned", pl: "nauczone", hr: "naučeno", sr: "naučeno",
               tr: "öğrenildi", sl: "naučeno" },
  notYet:    { de: "noch nicht geübt", en: "not practised yet", pl: "jeszcze nie ćwiczone",
               hr: "još nije vježbano", sr: "još nije vežbano", tr: "henüz çalışılmadı",
               sl: "še ni vadeno" },
  fresh:     { de: "sitzt", en: "retained", pl: "zapamiętane", hr: "zapamćeno",
               sr: "zapamćeno", tr: "oturmuş", sl: "zapomnjeno" },

  /* ---------------------------------------------------- Trainieren-Teil */
  trainHint: { de: "Zehn Karten pro Block. Was du nicht wusstest, kommt wieder — bis es sitzt.",
               en: "Ten cards per block. What you didn't know comes back — until it sticks.",
               pl: "Dziesięć kart na blok. Czego nie wiedziałeś, wraca — aż zapamiętasz.",
               hr: "Deset kartica po bloku. Što nisi znao, vraća se — dok ne sjedne.",
               sr: "Deset kartica po bloku. Što nisi znao, vraća se — dok ne sedne.",
               tr: "Blok başına on kart. Bilmediğin geri gelir — oturana kadar.",
               sl: "Deset kartic na blok. Česar nisi vedel, se vrne — dokler se ne usede." },

  /* ------------------------------------------------------ Karteikarten */
  ready:     { de: "Bereit?", en: "Ready?", pl: "Gotowy?", hr: "Spreman?", sr: "Spreman?",
               tr: "Hazır mısın?", sl: "Pripravljen?" },
  readyHint: { de: "Du siehst das deutsche Wort. Überleg dir die Übersetzung, dann dreh die Karte um.",
               en: "You see the German word. Think of the translation, then turn the card over.",
               pl: "Widzisz niemieckie słowo. Pomyśl o tłumaczeniu, potem odwróć kartę.",
               hr: "Vidiš njemačku riječ. Sjeti se prijevoda, pa okreni karticu.",
               sr: "Vidiš nemačku reč. Seti se prevoda, pa okreni karticu.",
               tr: "Almanca kelimeyi görürsün. Çevirisini düşün, sonra kartı çevir.",
               sl: "Vidiš nemško besedo. Pomisli na prevod, nato obrni kartico." },
  readyHintR:{ de: "Du siehst das Wort in deiner Sprache. Überleg dir das deutsche, dann dreh um.",
               en: "You see the word in your language. Think of the German one, then turn over.",
               pl: "Widzisz słowo w swoim języku. Pomyśl o niemieckim, potem odwróć.",
               hr: "Vidiš riječ na svom jeziku. Sjeti se njemačke, pa okreni.",
               sr: "Vidiš reč na svom jeziku. Seti se nemačke, pa okreni.",
               tr: "Kelimeyi kendi dilinde görürsün. Almancasını düşün, sonra çevir.",
               sl: "Vidiš besedo v svojem jeziku. Pomisli na nemško, nato obrni." },
  start:     { de: "Los geht's", en: "Let's go", pl: "Zaczynamy", hr: "Idemo", sr: "Idemo",
               tr: "Başlayalım", sl: "Gremo" },
  direction: { de: "Richtung", en: "Direction", pl: "Kierunek", hr: "Smjer", sr: "Smer",
               tr: "Yön", sl: "Smer" },
  flip:      { de: "Umdrehen", en: "Turn over", pl: "Odwróć", hr: "Okreni", sr: "Okreni",
               tr: "Çevir", sl: "Obrni" },
  knew:      { de: "Gewusst", en: "I knew it", pl: "Wiedziałem", hr: "Znao sam",
               sr: "Znao sam", tr: "Biliyordum", sl: "Vedel sem" },
  didntKnow: { de: "Nicht gewusst", en: "Didn't know", pl: "Nie wiedziałem",
               hr: "Nisam znao", sr: "Nisam znao", tr: "Bilmiyordum", sl: "Nisem vedel" },
  cards:     { de: "Karten", en: "cards", pl: "karty", hr: "kartice", sr: "kartice",
               tr: "kart", sl: "kartice" },
  cardAgain: { de: "Diese Karte kommt gleich noch einmal.",
               en: "This card will come back shortly.",
               pl: "Ta karta zaraz wróci.",
               hr: "Ova kartica će se uskoro ponoviti.",
               sr: "Ova kartica će se uskoro ponoviti.",
               tr: "Bu kart birazdan tekrar gelecek.",
               sl: "Ta kartica se bo kmalu ponovila." },
  remaining: { de: "übrig", en: "left", pl: "zostało", hr: "preostalo", sr: "preostalo",
               tr: "kaldı", sl: "ostalo" },
  knewN:     { de: "Gewusst", en: "Knew", pl: "Wiedziane", hr: "Znao", sr: "Znao",
               tr: "Bilinen", sl: "Vedel" },
  weakWords: { de: "Schwache Wörter üben", en: "Practise weak words", pl: "Ćwicz słabe słowa",
               hr: "Vježbaj slabe riječi", sr: "Vežbaj slabe reči",
               tr: "Zayıf kelimeleri çalış", sl: "Vadi šibke besede" },
  weakNone:  { de: "Noch nichts zum Auffrischen.", en: "Nothing to refresh yet.",
               pl: "Na razie nie ma czego powtarzać.", hr: "Još nema ništa za ponavljanje.",
               sr: "Još nema ništa za ponavljanje.", tr: "Henüz tazelenecek bir şey yok.",
               sl: "Zaenkrat ni ničesar za obnovo." },

  /* ---------------------------------------------------------- Kurs-Teil */
  courseHint: { de: "Der Kurs erklärt zusätzlich die Regeln: Abläufe, Hygiene, Sicherheit — mit Begründung.",
                en: "The course also explains the rules: procedures, hygiene, safety — with reasons.",
                pl: "Kurs wyjaśnia też zasady: procedury, higienę, bezpieczeństwo — z uzasadnieniem.",
                hr: "Tečaj objašnjava i pravila: postupke, higijenu, sigurnost — s obrazloženjem.",
                sr: "Kurs objašnjava i pravila: postupke, higijenu, bezbednost — sa obrazloženjem.",
                tr: "Kurs ayrıca kuralları açıklar: iş akışları, hijyen, güvenlik — gerekçesiyle.",
                sl: "Tečaj razloži tudi pravila: postopke, higieno, varnost — z utemeljitvijo." },
  refreshHead:{ de: "Zeit zum Auffrischen", en: "Time to refresh", pl: "Czas na powtórkę",
                hr: "Vrijeme za ponavljanje", sr: "Vreme za ponavljanje",
                tr: "Tazeleme zamanı", sl: "Čas za obnovo" },
  refreshBody:{ de: "sitzt nur noch zu", en: "is only retained at", pl: "jest zapamiętane tylko w",
                hr: "zapamćeno je samo", sr: "zapamćeno je samo",
                tr: "sadece şu kadar oturmuş:", sl: "je zapomnjeno le" },
  andMore:   { de: "weitere", en: "more", pl: "więcej", hr: "više", sr: "više",
               tr: "tane daha", sl: "več" },
  repeat:    { de: "Wiederholen", en: "Repeat", pl: "Powtórz", hr: "Ponovi", sr: "Ponovi",
               tr: "Tekrarla", sl: "Ponovi" },

  /* -------------------------------------------------------------- Player */
  whatMeans: { de: "Was bedeutet das?", en: "What does this mean?", pl: "Co to znaczy?",
               hr: "Što to znači?", sr: "Šta to znači?", tr: "Bu ne demek?",
               sl: "Kaj to pomeni?" },
  inYourLang:{ de: "In deiner Sprache:", en: "In your language:", pl: "W twoim języku:",
               hr: "Na tvom jeziku:", sr: "Na tvom jeziku:", tr: "Senin dilinde:",
               sl: "V tvojem jeziku:" },
  again:     { de: "Nochmal — das hattest du falsch", en: "Again — you had this wrong",
               pl: "Jeszcze raz — to miałeś źle", hr: "Još jednom — ovo si imao krivo",
               sr: "Još jednom — ovo si imao pogrešno", tr: "Tekrar — bunu yanlış yapmıştın",
               sl: "Še enkrat — to si imel narobe" },
  check:     { de: "Prüfen", en: "Check", pl: "Sprawdź", hr: "Provjeri", sr: "Proveri",
               tr: "Kontrol et", sl: "Preveri" },
  next:      { de: "Weiter", en: "Continue", pl: "Dalej", hr: "Dalje", sr: "Dalje",
               tr: "Devam", sl: "Naprej" },
  understood:{ de: "Verstanden", en: "Got it", pl: "Rozumiem", hr: "Razumijem",
               sr: "Razumem", tr: "Anladım", sl: "Razumem" },
  right:     { de: "Richtig", en: "Correct", pl: "Poprawnie", hr: "Točno", sr: "Tačno",
               tr: "Doğru", sl: "Pravilno" },
  wrong:     { de: "Nicht ganz", en: "Not quite", pl: "Nie całkiem", hr: "Nije baš",
               sr: "Nije baš", tr: "Tam değil", sl: "Ne čisto" },
  solution:  { de: "Richtige Antwort", en: "Correct answer", pl: "Poprawna odpowiedź",
               hr: "Točan odgovor", sr: "Tačan odgovor", tr: "Doğru cevap",
               sl: "Pravilen odgovor" },
  comesBack: { de: "Diese Aufgabe kommt gleich noch einmal.",
               en: "This exercise will come back shortly.",
               pl: "To zadanie zaraz wróci.",
               hr: "Ovaj zadatak će se uskoro ponoviti.",
               sr: "Ovaj zadatak će se uskoro ponoviti.",
               tr: "Bu alıştırma birazdan tekrar gelecek.",
               sl: "Ta naloga se bo kmalu ponovila." },
  tapWords:  { de: "Tippe die Wörter in der richtigen Reihenfolge an",
               en: "Tap the words in the right order",
               pl: "Dotykaj słów we właściwej kolejności",
               hr: "Dodirni riječi ispravnim redoslijedom",
               sr: "Dodirni reči ispravnim redosledom",
               tr: "Kelimelere doğru sırayla dokun",
               sl: "Klikni besede v pravilnem vrstnem redu" },
  tapSteps:  { de: "Tippe die Schritte in der richtigen Reihenfolge an",
               en: "Tap the steps in the right order",
               pl: "Dotykaj kroków we właściwej kolejności",
               hr: "Dodirni korake ispravnim redoslijedom",
               sr: "Dodirni korake ispravnim redosledom",
               tr: "Adımlara doğru sırayla dokun",
               sl: "Klikni korake v pravilnem vrstnem redu" },
  tfTrue:    { de: "Richtig", en: "True", pl: "Prawda", hr: "Točno", sr: "Tačno",
               tr: "Doğru", sl: "Pravilno" },
  tfFalse:   { de: "Falsch", en: "False", pl: "Fałsz", hr: "Netočno", sr: "Netačno",
               tr: "Yanlış", sl: "Napačno" },
  freeSlots: { de: "frei", en: "free", pl: "wolne", hr: "slobodno", sr: "slobodno",
               tr: "boş", sl: "prosto" },
  of:        { de: "von", en: "of", pl: "z", hr: "od", sr: "od", tr: "/", sl: "od" },

  /* --------------------------------------------------------- Herzen leer */
  noHearts:  { de: "Herzen alle", en: "Out of hearts", pl: "Koniec serc",
               hr: "Nema više srca", sr: "Nema više srca", tr: "Kalpler bitti",
               sl: "Zmanjkalo src" },
  noHeartsMsg:{ de: "Du hast zu oft geraten. Es geht von vorne los — mit fünf neuen Herzen.",
                en: "Too many wrong guesses. You start over — with five fresh hearts.",
                pl: "Za dużo błędów. Zaczynasz od nowa — z pięcioma nowymi sercami.",
                hr: "Previše pogrešaka. Počinješ ispočetka — s pet novih srca.",
                sr: "Previše grešaka. Počinješ iz početka — sa pet novih srca.",
                tr: "Çok fazla yanlış yaptın. Baştan başlıyorsun — beş yeni kalple.",
                sl: "Preveč napak. Začneš znova — s petimi novimi srci." },
  restart:   { de: "Nochmal starten", en: "Start again", pl: "Zacznij od nowa",
               hr: "Počni ispočetka", sr: "Počni iz početka", tr: "Yeniden başla",
               sl: "Začni znova" },

  /* ----------------------------------------------------------- Abschluss */
  perfect:   { de: "Perfekt!", en: "Perfect!", pl: "Idealnie!", hr: "Savršeno!",
               sr: "Savršeno!", tr: "Mükemmel!", sl: "Odlično!" },
  done:      { de: "Geschafft!", en: "Done!", pl: "Udało się!", hr: "Uspjelo!",
               sr: "Uspelo!", tr: "Başardın!", sl: "Uspelo je!" },
  perfectSub:{ de: "Jede Karte auf Anhieb gewusst.", en: "Every card known first time.",
               pl: "Każda karta znana za pierwszym razem.", hr: "Svaku karticu znao iz prve.",
               sr: "Svaku karticu znao iz prve.", tr: "Her kartı ilk seferde bildin.",
               sl: "Vsako kartico si vedel v prvo." },
  doneSub:   { de: "Du hast jede Aufgabe richtig gelöst — auch die, die du wiederholen musstest.",
               en: "You solved every exercise correctly — including the ones you had to repeat.",
               pl: "Rozwiązałeś poprawnie każde zadanie — także te, które musiałeś powtórzyć.",
               hr: "Riješio si svaki zadatak točno — i one koje si morao ponoviti.",
               sr: "Rešio si svaki zadatak tačno — i one koje si morao da ponoviš.",
               tr: "Her alıştırmayı doğru çözdün — tekrar etmen gerekenleri de.",
               sl: "Vsako nalogo si rešil pravilno — tudi tiste, ki si jih moral ponoviti." },
  retriedN:  { de: "Wiederholt", en: "Repeated", pl: "Powtórzone", hr: "Ponovljeno",
               sr: "Ponovljeno", tr: "Tekrarlanan", sl: "Ponovljeno" },
  close:     { de: "Weiter", en: "Continue", pl: "Dalej", hr: "Dalje", sr: "Dalje",
               tr: "Devam", sl: "Naprej" }
};
